// AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).
// DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.

package aozora

const SchemaVersion = 3

type AozoraJSON struct {
	AozoraContainerPairsEnvelope *AozoraContainerPairsEnvelope `json:"AozoraContainerPairsEnvelope,omitempty"`
	AozoraDiagnosticsEnvelope    *AozoraDiagnosticsEnvelope    `json:"AozoraDiagnosticsEnvelope,omitempty"`
	AozoraGaijiEnvelope          *AozoraGaijiEnvelope          `json:"AozoraGaijiEnvelope,omitempty"`
	AozoraNodesEnvelope          *AozoraNodesEnvelope          `json:"AozoraNodesEnvelope,omitempty"`
	AozoraPairsEnvelope          *AozoraPairsEnvelope          `json:"AozoraPairsEnvelope,omitempty"`
	AozoraSlugsEnvelope          *AozoraSlugsEnvelope          `json:"AozoraSlugsEnvelope,omitempty"`
}

type AozoraContainerPairsEnvelope struct {
	Data          []ContainerPair `json:"data"`
	SchemaVersion int64           `json:"schemaVersion"`
}

// One `container_pairs` envelope entry.
type ContainerPair struct {
	Close Span   `json:"close"`
	Kind  string `json:"kind"`
	Open  Span   `json:"open"`
}

// One half-open `[start, end)` byte span in a wire envelope.
type Span struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type AozoraDiagnosticsEnvelope struct {
	Data          []Diagnostic `json:"data"`
	SchemaVersion int64        `json:"schemaVersion"`
}

// One `diagnostics` envelope entry — a projected [`crate::Diagnostic`].
type Diagnostic struct {
	Codepoint *int64 `json:"codepoint"`
	Kind      string `json:"kind"`
	Severity  string `json:"severity"`
	Source    string `json:"source"`
	Span      Span   `json:"span"`
}

type AozoraGaijiEnvelope struct {
	Data          []GaijiResolution `json:"data"`
	SchemaVersion int64             `json:"schemaVersion"`
}

// One `gaiji` envelope entry — a resolved `※［＃…］` reference.
type GaijiResolution struct {
	Codepoint   *int64  `json:"codepoint"`
	Description string  `json:"description"`
	Mencode     *string `json:"mencode"`
	Resolved    *string `json:"resolved"`
	Span        Span    `json:"span"`
}

type AozoraNodesEnvelope struct {
	Data          []Node `json:"data"`
	SchemaVersion int64  `json:"schemaVersion"`
}

// One `nodes` envelope entry — a classified node span in source coords.
type Node struct {
	Kind string `json:"kind"`
	Span Span   `json:"span"`
}

type AozoraPairsEnvelope struct {
	Data          []Pair `json:"data"`
	SchemaVersion int64  `json:"schemaVersion"`
}

// One `pairs` envelope entry — a matched bracket pair.
type Pair struct {
	Close Span   `json:"close"`
	Kind  string `json:"kind"`
	Open  Span   `json:"open"`
}

type AozoraSlugsEnvelope struct {
	Data          []Slug `json:"data"`
	SchemaVersion int64  `json:"schemaVersion"`
}

// One `slugs` envelope entry — a row of the annotation slug catalogue.
type Slug struct {
	AcceptsParam bool    `json:"accepts_param"`
	Canonical    string  `json:"canonical"`
	Doc          string  `json:"doc"`
	Family       string  `json:"family"`
	Partner      *string `json:"partner"`
}
