// AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).
// DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.

package aozora

type AozoraJSON struct {
	AozoraContainerPairsEnvelope *AozoraContainerPairsEnvelope `json:"AozoraContainerPairsEnvelope,omitempty"`
	AozoraDiagnosticsEnvelope    *AozoraDiagnosticsEnvelope    `json:"AozoraDiagnosticsEnvelope,omitempty"`
	AozoraNodesEnvelope          *AozoraNodesEnvelope          `json:"AozoraNodesEnvelope,omitempty"`
	AozoraPairsEnvelope          *AozoraPairsEnvelope          `json:"AozoraPairsEnvelope,omitempty"`
}

type AozoraContainerPairsEnvelope struct {
	Data          []ContainerPair `json:"data"`
	SchemaVersion int64           `json:"schemaVersion"`
}

// One `container_pairs` envelope entry — a paired container, open/close
// in normalized coordinates.
type ContainerPair struct {
	Close Offset `json:"close"`
	Kind  string `json:"kind"`
	Open  Offset `json:"open"`
}

// A single byte offset (a `container_pairs` open/close in normalized
// coordinates).
type Offset struct {
	Offset int64 `json:"offset"`
}

type AozoraDiagnosticsEnvelope struct {
	Data          []Diagnostic `json:"data"`
	SchemaVersion int64        `json:"schemaVersion"`
}

// One `diagnostics` envelope entry — a projected [`crate::Diagnostic`].
type Diagnostic struct {
	Codepoint *string `json:"codepoint"`
	Kind      string  `json:"kind"`
	Severity  string  `json:"severity"`
	Source    string  `json:"source"`
	Span      Span    `json:"span"`
}

// One half-open `[start, end)` byte span in a wire envelope.
type Span struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type AozoraNodesEnvelope struct {
	Data          []Node `json:"data"`
	SchemaVersion int64  `json:"schemaVersion"`
}

// One `nodes` envelope entry — a classified node span in source coords.
type Node struct {
	Kind string `json:"kind"`
	Span Span   `json:"span"`
}

type AozoraPairsEnvelope struct {
	Data          []Pair `json:"data"`
	SchemaVersion int64  `json:"schemaVersion"`
}

// One `pairs` envelope entry — a matched bracket pair.
type Pair struct {
	Close Span   `json:"close"`
	Kind  string `json:"kind"`
	Open  Span   `json:"open"`
}
