// AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).
// DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.

package aozora

type AozoraWire struct {
	AozoraContainerPairsEnvelope *AozoraContainerPairsEnvelope `json:"AozoraContainerPairsEnvelope,omitempty"`
	AozoraDiagnosticsEnvelope    *AozoraDiagnosticsEnvelope    `json:"AozoraDiagnosticsEnvelope,omitempty"`
	AozoraNodesEnvelope          *AozoraNodesEnvelope          `json:"AozoraNodesEnvelope,omitempty"`
	AozoraPairsEnvelope          *AozoraPairsEnvelope          `json:"AozoraPairsEnvelope,omitempty"`
}

type AozoraContainerPairsEnvelope struct {
	Data          []ContainerPairWire `json:"data"`
	SchemaVersion int64               `json:"schema_version"`
}

type ContainerPairWire struct {
	Close OffsetWire `json:"close"`
	Kind  string     `json:"kind"`
	Open  OffsetWire `json:"open"`
}

type OffsetWire struct {
	Offset int64 `json:"offset"`
}

type AozoraDiagnosticsEnvelope struct {
	Data          []DiagnosticWire `json:"data"`
	SchemaVersion int64            `json:"schema_version"`
}

type DiagnosticWire struct {
	Codepoint *string  `json:"codepoint"`
	Kind      string   `json:"kind"`
	Severity  string   `json:"severity"`
	Source    string   `json:"source"`
	Span      SpanWire `json:"span"`
}

type SpanWire struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type AozoraNodesEnvelope struct {
	Data          []NodeWire `json:"data"`
	SchemaVersion int64      `json:"schema_version"`
}

type NodeWire struct {
	Kind string   `json:"kind"`
	Span SpanWire `json:"span"`
}

type AozoraPairsEnvelope struct {
	Data          []PairWire `json:"data"`
	SchemaVersion int64      `json:"schema_version"`
}

type PairWire struct {
	Close SpanWire `json:"close"`
	Kind  string   `json:"kind"`
	Open  SpanWire `json:"open"`
}
