/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_gaiji = 1,
  sym_slug = 2,
  sym_explicit_ruby = 3,
  sym_implicit_ruby = 4,
  sym_text = 5,
  sym_newline = 6,
  sym_literal_markup = 7,
  sym_document = 8,
  sym__element = 9,
  aux_sym_document_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_gaiji] = "gaiji",
  [sym_slug] = "slug",
  [sym_explicit_ruby] = "explicit_ruby",
  [sym_implicit_ruby] = "implicit_ruby",
  [sym_text] = "text",
  [sym_newline] = "newline",
  [sym_literal_markup] = "literal_markup",
  [sym_document] = "document",
  [sym__element] = "_element",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_gaiji] = sym_gaiji,
  [sym_slug] = sym_slug,
  [sym_explicit_ruby] = sym_explicit_ruby,
  [sym_implicit_ruby] = sym_implicit_ruby,
  [sym_text] = sym_text,
  [sym_newline] = sym_newline,
  [sym_literal_markup] = sym_literal_markup,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_gaiji] = {
    .visible = true,
    .named = true,
  },
  [sym_slug] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_ruby] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_ruby] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_markup] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 19,
        0x203b, 22,
        0x300a, 20,
        0xff3b, 21,
        0xff5c, 23,
        0x300b, 16,
        0xff03, 16,
        0xff3d, 16,
      );
      if (lookahead == 0x3005 ||
          lookahead == 0x30f5 ||
          lookahead == 0x30f6 ||
          (0x3400 <= lookahead && lookahead <= 0x4dbf) ||
          (0x4e00 <= lookahead && lookahead <= 0x9fff) ||
          (0xf900 <= lookahead && lookahead <= 0xfaff)) ADVANCE(17);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == 0x300a) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0xff5c) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 0x300b) ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 0x300b) ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == 0xff03) ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 0xff3d) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 0xff3d) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x300b) ADVANCE(2);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x300b) ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0xff3d) ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0xff3d) ADVANCE(6);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_gaiji);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_slug);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_explicit_ruby);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_implicit_ruby);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 0x300a) ADVANCE(7);
      if (lookahead == 0x3005 ||
          lookahead == 0x30f5 ||
          lookahead == 0x30f6 ||
          (0x3400 <= lookahead && lookahead <= 0x4dbf) ||
          (0x4e00 <= lookahead && lookahead <= 0x9fff) ||
          (0xf900 <= lookahead && lookahead <= 0xfaff)) ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x203b &&
          lookahead != 0x300a &&
          lookahead != 0x300b &&
          lookahead != 0xff03 &&
          lookahead != 0xff3b &&
          lookahead != 0xff3d &&
          lookahead != 0xff5c) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x203b &&
          lookahead != 0x300a &&
          lookahead != 0x300b &&
          lookahead != 0xff03 &&
          lookahead != 0xff3b &&
          lookahead != 0xff3d &&
          lookahead != 0xff5c) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_literal_markup);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_literal_markup);
      if (lookahead == 0xff03) ADVANCE(9);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_literal_markup);
      if (lookahead == 0xff3b) ADVANCE(4);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_literal_markup);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x300a &&
          lookahead != 0xff5c) ADVANCE(1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_gaiji] = ACTIONS(1),
    [sym_slug] = ACTIONS(1),
    [sym_explicit_ruby] = ACTIONS(1),
    [sym_implicit_ruby] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_literal_markup] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(4),
    [sym__element] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_gaiji] = ACTIONS(5),
    [sym_slug] = ACTIONS(5),
    [sym_explicit_ruby] = ACTIONS(5),
    [sym_implicit_ruby] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [sym_newline] = ACTIONS(5),
    [sym_literal_markup] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__element] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_gaiji] = ACTIONS(11),
    [sym_slug] = ACTIONS(11),
    [sym_explicit_ruby] = ACTIONS(11),
    [sym_implicit_ruby] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_newline] = ACTIONS(11),
    [sym_literal_markup] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__element] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_gaiji] = ACTIONS(17),
    [sym_slug] = ACTIONS(17),
    [sym_explicit_ruby] = ACTIONS(17),
    [sym_implicit_ruby] = ACTIONS(17),
    [sym_text] = ACTIONS(20),
    [sym_newline] = ACTIONS(17),
    [sym_literal_markup] = ACTIONS(20),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aozora(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
