//! Phase L2 — TypeScript types artefact dump / drift gate.
//!
//! Generates `crates/aozora-wasm/types/aozora_types.d.ts` directly
//! from the live Rust enums and wire structs. The output is a
//! discriminated-union `.d.ts` consumable by `Obsidian` / `VSCode` /
//! plugin authors via:
//!
//! ```text
//! import type { NodeKind, DiagnosticWire } from "aozora-wasm/aozora_types";
//! ```
//!
//! The source of truth lives outside `pkg/` because `wasm-pack`
//! wipes that directory on rebuild. A future packaging step copies
//! this file into `pkg/` before `npm publish`.
//!
//! Drift-gated by `xtask types check`. The `Obsidian` / `VSCode` /
//! Pandoc plugin authors are the primary consumers.
//!
//! Drift-gated by `xtask types check` so a new `NodeKind` variant
//! lands as a build-time CI failure if the artefact regen step is
//! forgotten. The aozora-syntax / aozora-spec ALL constants drive
//! the codegen — adding a variant flows automatically into the
//! generated output once the ALL array is updated.

use std::fs;
use std::path::{Path, PathBuf};

use aozora::pipeline::{NodeRef, PairKind};
use aozora::syntax::NodeKind;
use aozora::{DiagnosticSource, InternalCheckCode, Sentinel, Severity};

use crate::TypesArgs;
use crate::TypesOp;

const TYPES_REL_PATH: &str = "crates/aozora-wasm/types/aozora_types.d.ts";

pub(crate) fn dispatch(args: &TypesArgs) -> Result<(), String> {
    match args.op {
        TypesOp::Ts => dump(),
        TypesOp::Check => check(),
    }
}

fn workspace_root() -> Result<PathBuf, String> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let root = Path::new(manifest_dir)
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!("could not derive workspace root from CARGO_MANIFEST_DIR={manifest_dir:?}")
        })?;
    Ok(root.to_path_buf())
}

/// Render a Rust slice of enum variants into a TypeScript
/// string-literal union: `"a" | "b" | "c"`. Variants are projected
/// to their wire string via the supplied closure.
fn ts_string_union<T: Copy>(values: &[T], to_wire: impl Fn(T) -> &'static str) -> String {
    values
        .iter()
        .map(|v| format!("\"{}\"", to_wire(*v)))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Append `export type {name} = {union};` followed by a blank line.
/// Centralised here so `render_enums` stays free of `writeln!`-into-String
/// boilerplate (and the associated `let_underscore_must_use` clippy noise).
fn push_export_type(out: &mut String, name: &str, union: &str) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    out.push_str(union);
    out.push_str(";\n\n");
}

fn render() -> String {
    let mut out = String::new();
    render_header(&mut out);
    render_enums(&mut out);
    render_wire_payloads(&mut out);
    render_envelopes(&mut out);
    out
}

fn render_header(out: &mut String) {
    out.push_str("// AUTO-GENERATED by `xtask types ts` — DO NOT EDIT BY HAND.\n");
    out.push_str("// Regenerate with `just types-ts` (or `xtask types ts`); commit the diff.\n");
    out.push_str("// Drift-gated in CI by `xtask types check`.\n");
    out.push('\n');
}

fn render_enums(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Enums (string-literal unions matching wire `kind` field)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Cross-cutting tag for an AST node or `NodeRef` projection. */\n");
    push_export_type(
        out,
        "NodeKind",
        &ts_string_union(&NodeKind::ALL, NodeKind::as_camel_case),
    );
    out.push_str("/** Pair kind for `pairs_json` output. */\n");
    push_export_type(
        out,
        "PairKind",
        &ts_string_union(&PairKind::ALL, PairKind::as_camel_case),
    );
    out.push_str("/** Diagnostic severity tier (wire field `severity`). */\n");
    push_export_type(
        out,
        "Severity",
        &ts_string_union(&Severity::ALL, Severity::as_wire_str),
    );
    out.push_str(
        "/** Diagnostic origin (wire field `source`). `internal` indicates a library bug. */\n",
    );
    push_export_type(
        out,
        "DiagnosticSource",
        &ts_string_union(&DiagnosticSource::ALL, DiagnosticSource::as_wire_str),
    );
    out.push_str("/** Stable namespaced ID for an Internal sanity-check failure. */\n");
    push_export_type(
        out,
        "InternalCheckCode",
        &ts_string_union(&InternalCheckCode::ALL, InternalCheckCode::as_code),
    );
    out.push_str("/** PUA sentinel codepoint kind (4 reserved markers in `U+E001..U+E004`). */\n");
    push_export_type(
        out,
        "SentinelKind",
        &ts_string_union(&Sentinel::ALL, sentinel_to_wire),
    );
}

/// Module-level static assertion that pins the `Sentinel`→`NodeRef`
/// linkage at compile time. If `NodeRef::sentinel_kind` is ever removed
/// or has its signature changed, this `const` fails to type-check —
/// catching the drift before the TS artefact silently goes stale.
const _ASSERT_SENTINEL_KIND_EXISTS: fn(NodeRef<'static>) -> Sentinel = NodeRef::sentinel_kind;

fn render_wire_payloads(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Wire envelope payload types\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str(
        "/** Half-open byte span `[start, end)` in the relevant coordinate system\n\
         (sanitized source for diagnostics / nodes / pairs; see `aozora::wire` docs). */\n",
    );
    out.push_str("export interface SpanWire {\n  start: number;\n  end: number;\n}\n\n");
    out.push_str(
        "/** Single byte offset (used by `ContainerPairWire` open / close in normalized coords). */\n",
    );
    out.push_str("export interface OffsetWire {\n  offset: number;\n}\n\n");
    out.push_str("/** One entry of `serialize_diagnostics` — `Diagnostic` projection. */\n");
    out.push_str(
        "export interface DiagnosticWire {\n  /** Variant tag (last segment of `Diagnostic::code()`, e.g. `\"source_contains_pua\"`). */\n  kind: string;\n  severity: Severity;\n  source: DiagnosticSource;\n  span: SpanWire;\n  /** Codepoint payload (only `SourceContainsPua` carries one today). */\n  codepoint?: string;\n}\n\n",
    );
    out.push_str(
        "/** One entry of `serialize_nodes` — classified `AozoraNode` span in source coords. */\n",
    );
    out.push_str("export interface NodeWire {\n  kind: NodeKind;\n  span: SpanWire;\n}\n\n");
    out.push_str("/** One entry of `serialize_pairs` — matched bracket pair link. */\n");
    out.push_str(
        "export interface PairWire {\n  kind: PairKind;\n  open: SpanWire;\n  close: SpanWire;\n}\n\n",
    );
    out.push_str(
        "/** One entry of `serialize_container_pairs` — paired container (open in normalized coords). */\n",
    );
    out.push_str(
        "export interface ContainerPairWire {\n  kind: \"indent\" | \"warichu\" | \"keigakomi\" | \"alignEnd\" | \"unknown\";\n  open: OffsetWire;\n  close: OffsetWire;\n}\n\n",
    );
}

fn render_envelopes(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Envelopes (top-level shape returned by every wire endpoint)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Generic wire envelope. Every endpoint emits this top-level shape. */\n");
    out.push_str(
        "export interface WireEnvelope<T> {\n  schema_version: 1;\n  data: ReadonlyArray<T>;\n}\n\n",
    );
    out.push_str("export type DiagnosticsEnvelope    = WireEnvelope<DiagnosticWire>;\n");
    out.push_str("export type NodesEnvelope          = WireEnvelope<NodeWire>;\n");
    out.push_str("export type PairsEnvelope          = WireEnvelope<PairWire>;\n");
    out.push_str("export type ContainerPairsEnvelope = WireEnvelope<ContainerPairWire>;\n");
}

fn sentinel_to_wire(s: Sentinel) -> &'static str {
    // Sentinels don't have a public wire string of their own (the
    // wire NodeWire kind already covers ContainerOpen/Close); we
    // emit lowercase variant names here so the `SentinelKind` TS
    // type stays useful for reading raw NormalizedOffset coordinate
    // metadata.
    match s {
        Sentinel::Inline => "inline",
        Sentinel::BlockLeaf => "blockLeaf",
        Sentinel::BlockOpen => "blockOpen",
        Sentinel::BlockClose => "blockClose",
    }
}

fn dump() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
    }
    fs::write(&path, render())
        .map_err(|err| format!("write types artefact {}: {err}", path.display()))?;
    eprintln!("xtask types ts: wrote {}", path.display());
    Ok(())
}

fn check() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    let actual = render();
    let stored = fs::read_to_string(&path)
        .map_err(|err| format!("read types artefact {}: {err}", path.display()))?;
    if actual == stored {
        eprintln!("xtask types check: aozora_types.d.ts up to date");
        Ok(())
    } else {
        Err(format!(
            "TypeScript types drift detected in {TYPES_REL_PATH}:\n  \
             run `xtask types ts` to regenerate, then commit"
        ))
    }
}
