//! TypeScript types artefact dump / drift gate.
//!
//! Generates `crates/aozora-wasm/types/aozora_types.d.ts` directly
//! from the live Rust enums and wire structs. The output is a
//! discriminated-union `.d.ts` for downstream TypeScript consumers:
//!
//! ```text
//! import type { NodeKind, DiagnosticWire } from "aozora-wasm/aozora_types";
//! ```
//!
//! The source of truth lives outside `pkg/` because `wasm-pack`
//! wipes that directory on rebuild. A future packaging step copies
//! this file into `pkg/` before `npm publish`.
//!
//! Drift-gated by `xtask types check` so a new `NodeKind` variant
//! lands as a build-time CI failure if the artefact regen step is
//! forgotten. The aozora-syntax / aozora-spec ALL constants drive
//! the codegen — adding a variant flows automatically into the
//! generated output once the ALL array is updated.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{Map, Value};

use aozora::pipeline::{NodeRef, PairKind};
use aozora::syntax::NodeKind;
use aozora::{DiagnosticSource, InternalCheckCode, Sentinel, Severity};

use crate::TypesArgs;
use crate::TypesOp;
use crate::schema::SCHEMA_FILES;

const TYPES_REL_PATH: &str = "crates/aozora-wasm/types/aozora_types.d.ts";

pub(crate) fn dispatch(args: &TypesArgs) -> Result<(), String> {
    match args.op {
        TypesOp::Ts => dump(),
        TypesOp::Check => check(),
        TypesOp::Langs => langs_dump(),
        TypesOp::LangsCheck => langs_check(),
    }
}

fn workspace_root() -> Result<PathBuf, String> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let root = Path::new(manifest_dir)
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!("could not derive workspace root from CARGO_MANIFEST_DIR={manifest_dir:?}")
        })?;
    Ok(root.to_path_buf())
}

/// Render a Rust slice of enum variants into a TypeScript
/// string-literal union: `"a" | "b" | "c"`. Variants are projected
/// to their wire string via the supplied closure.
fn ts_string_union<T: Copy>(values: &[T], to_wire: impl Fn(T) -> &'static str) -> String {
    values
        .iter()
        .map(|v| format!("\"{}\"", to_wire(*v)))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Append `export type {name} = {union};` followed by a blank line.
/// Centralised here so `render_enums` stays free of `writeln!`-into-String
/// boilerplate (and the associated `let_underscore_must_use` clippy noise).
fn push_export_type(out: &mut String, name: &str, union: &str) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    out.push_str(union);
    out.push_str(";\n\n");
}

fn render() -> String {
    let mut out = String::new();
    render_header(&mut out);
    render_enums(&mut out);
    render_wire_payloads(&mut out);
    render_envelopes(&mut out);
    out
}

fn render_header(out: &mut String) {
    out.push_str("// AUTO-GENERATED by `xtask types ts` — DO NOT EDIT BY HAND.\n");
    out.push_str("// Regenerate with `just types-ts` (or `xtask types ts`); commit the diff.\n");
    out.push_str("// Drift-gated in CI by `xtask types check`.\n");
    out.push('\n');
}

fn render_enums(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Enums (string-literal unions matching wire `kind` field)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Cross-cutting tag for an AST node or `NodeRef` projection. */\n");
    push_export_type(
        out,
        "NodeKind",
        &ts_string_union(&NodeKind::ALL, NodeKind::as_camel_case),
    );
    out.push_str("/** Pair kind for `pairs_json` output. */\n");
    push_export_type(
        out,
        "PairKind",
        &ts_string_union(&PairKind::ALL, PairKind::as_camel_case),
    );
    out.push_str("/** Diagnostic severity tier (wire field `severity`). */\n");
    push_export_type(
        out,
        "Severity",
        &ts_string_union(&Severity::ALL, Severity::as_wire_str),
    );
    out.push_str(
        "/** Diagnostic origin (wire field `source`). `internal` indicates a library bug. */\n",
    );
    push_export_type(
        out,
        "DiagnosticSource",
        &ts_string_union(&DiagnosticSource::ALL, DiagnosticSource::as_wire_str),
    );
    out.push_str("/** Stable namespaced ID for an Internal sanity-check failure. */\n");
    push_export_type(
        out,
        "InternalCheckCode",
        &ts_string_union(&InternalCheckCode::ALL, InternalCheckCode::as_code),
    );
    out.push_str("/** PUA sentinel codepoint kind (4 reserved markers in `U+E001..U+E004`). */\n");
    push_export_type(
        out,
        "SentinelKind",
        &ts_string_union(&Sentinel::ALL, sentinel_to_wire),
    );
}

/// Module-level static assertion that pins the `Sentinel`→`NodeRef`
/// linkage at compile time. If `NodeRef::sentinel_kind` is ever removed
/// or has its signature changed, this `const` fails to type-check —
/// catching the drift before the TS artefact silently goes stale.
const _ASSERT_SENTINEL_KIND_EXISTS: fn(NodeRef<'static>) -> Sentinel = NodeRef::sentinel_kind;

fn render_wire_payloads(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Wire envelope payload types\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str(
        "/** Half-open byte span `[start, end)` in the relevant coordinate system\n\
         (sanitized source for diagnostics / nodes / pairs; see `aozora::wire` docs). */\n",
    );
    out.push_str("export interface SpanWire {\n  start: number;\n  end: number;\n}\n\n");
    out.push_str(
        "/** Single byte offset (used by `ContainerPairWire` open / close in normalized coords). */\n",
    );
    out.push_str("export interface OffsetWire {\n  offset: number;\n}\n\n");
    out.push_str("/** One entry of `serialize_diagnostics` — `Diagnostic` projection. */\n");
    out.push_str(
        "export interface DiagnosticWire {\n  /** Variant tag (last segment of `Diagnostic::code()`, e.g. `\"source_contains_pua\"`). */\n  kind: string;\n  severity: Severity;\n  source: DiagnosticSource;\n  span: SpanWire;\n  /** Codepoint payload (only `SourceContainsPua` carries one today). */\n  codepoint?: string;\n}\n\n",
    );
    out.push_str(
        "/** One entry of `serialize_nodes` — classified `AozoraNode` span in source coords. */\n",
    );
    out.push_str("export interface NodeWire {\n  kind: NodeKind;\n  span: SpanWire;\n}\n\n");
    out.push_str("/** One entry of `serialize_pairs` — matched bracket pair link. */\n");
    out.push_str(
        "export interface PairWire {\n  kind: PairKind;\n  open: SpanWire;\n  close: SpanWire;\n}\n\n",
    );
    out.push_str(
        "/** One entry of `serialize_container_pairs` — paired container (open in normalized coords). */\n",
    );
    out.push_str(
        "export interface ContainerPairWire {\n  kind: \"indent\" | \"warichu\" | \"keigakomi\" | \"alignEnd\" | \"boutenRange\" | \"bold\" | \"italic\" | \"unknown\";\n  open: OffsetWire;\n  close: OffsetWire;\n}\n\n",
    );
}

fn render_envelopes(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Envelopes (top-level shape returned by every wire endpoint)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Generic wire envelope. Every endpoint emits this top-level shape. */\n");
    out.push_str(
        "export interface WireEnvelope<T> {\n  schema_version: 1;\n  data: ReadonlyArray<T>;\n}\n\n",
    );
    out.push_str("export type DiagnosticsEnvelope    = WireEnvelope<DiagnosticWire>;\n");
    out.push_str("export type NodesEnvelope          = WireEnvelope<NodeWire>;\n");
    out.push_str("export type PairsEnvelope          = WireEnvelope<PairWire>;\n");
    out.push_str("export type ContainerPairsEnvelope = WireEnvelope<ContainerPairWire>;\n");
}

fn sentinel_to_wire(s: Sentinel) -> &'static str {
    // Sentinels don't have a public wire string of their own (the
    // wire NodeWire kind already covers ContainerOpen/Close); we
    // emit lowercase variant names here so the `SentinelKind` TS
    // type stays useful for reading raw NormalizedOffset coordinate
    // metadata.
    match s {
        Sentinel::Inline => "inline",
        Sentinel::BlockLeaf => "blockLeaf",
        Sentinel::BlockOpen => "blockOpen",
        Sentinel::BlockClose => "blockClose",
    }
}

fn dump() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
    }
    fs::write(&path, render())
        .map_err(|err| format!("write types artefact {}: {err}", path.display()))?;
    eprintln!("xtask types ts: wrote {}", path.display());
    Ok(())
}

fn check() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    let actual = render();
    let stored = fs::read_to_string(&path)
        .map_err(|err| format!("read types artefact {}: {err}", path.display()))?;
    if actual == stored {
        eprintln!("xtask types check: aozora_types.d.ts up to date");
        Ok(())
    } else {
        Err(format!(
            "TypeScript types drift detected in {TYPES_REL_PATH}:\n  \
             run `xtask types ts` to regenerate, then commit"
        ))
    }
}

// ────────────────────────────────────────────────────────────────────
// Per-language wire types via quicktype (`xtask types langs`)
// ────────────────────────────────────────────────────────────────────
//
// The TypeScript `.d.ts` above is hand-rolled from the live Rust enums
// (it needs the string-literal unions for `NodeKind` etc. that the JSON
// Schema erases to plain `string`). Every *other* host-SDK language is
// generated mechanically by `quicktype` from the committed wire JSON
// Schema — one generator, all languages — so adding a language is a
// single row in `LANG_TYPES`, not a new codegen backend.

/// One target language for `quicktype`-generated wire types.
struct LangType {
    /// Display name (and the key used in drift messages).
    name: &'static str,
    /// `quicktype --lang` identifier.
    quicktype_lang: &'static str,
    /// Output path, relative to the workspace root. Committed + drift-gated.
    out: &'static str,
    /// Line-comment prefix for the generated-file header.
    comment: &'static str,
    /// Text inserted between the header and the generated body — e.g. a
    /// Go `package` clause (quicktype's `--just-types` omits it).
    prelude: &'static str,
    /// Extra `quicktype` flags.
    extra: &'static [&'static str],
    /// When `true`, pipe the output through `gofmt` so the committed
    /// artifact matches what the host package's own `gofmt` gate expects.
    gofmt: bool,
}

/// The languages we generate wire types for. Adding a host SDK is one
/// row here plus a `crates/aozora-<lang>/` package that consumes the file.
const LANG_TYPES: &[LangType] = &[LangType {
    name: "go",
    quicktype_lang: "go",
    out: "crates/aozora-go/wire_gen.go",
    comment: "// ",
    prelude: "package aozora\n\n",
    extra: &["--just-types", "--top-level", "AozoraWire"],
    gofmt: true,
}];

fn langs_dump() -> Result<(), String> {
    let root = workspace_root()?;
    let combined = write_combined_schema(&root)?;
    for lt in LANG_TYPES {
        let body = generate_lang(lt, &combined)?;
        let path = root.join(lt.out);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
        }
        fs::write(&path, &body)
            .map_err(|err| format!("write {} types {}: {err}", lt.name, path.display()))?;
        eprintln!("xtask types langs: wrote {}", path.display());
    }
    Ok(())
}

fn langs_check() -> Result<(), String> {
    let root = workspace_root()?;
    let combined = write_combined_schema(&root)?;
    let mut drift = Vec::new();
    for lt in LANG_TYPES {
        let actual = generate_lang(lt, &combined)?;
        let path = root.join(lt.out);
        let stored = fs::read_to_string(&path)
            .map_err(|err| format!("read {} types {}: {err}", lt.name, path.display()))?;
        if actual != stored {
            drift.push(lt.out.to_owned());
        }
    }
    if drift.is_empty() {
        eprintln!(
            "xtask types langs-check: {}/{} per-language wire types up to date",
            LANG_TYPES.len(),
            LANG_TYPES.len()
        );
        Ok(())
    } else {
        Err(format!(
            "per-language wire types drift detected in {} file(s):\n  {}\n\
             run `xtask types langs` to regenerate, then commit",
            drift.len(),
            drift.join("\n  "),
        ))
    }
}

/// Build one combined JSON Schema from the four committed per-envelope
/// schemas and write it to a temp file `quicktype` can consume. Returns
/// the temp path.
///
/// Why combine: feeding the four schema files to `quicktype` separately
/// makes it invent distinct names for the structurally-identical inner
/// types (`PurpleSpan`, `FluffySpan`, …). One document with a shared
/// `$defs` yields a single `SpanWire` / `OffsetWire`. Two transforms make
/// it digestible: every `$def` gets a `title` equal to its key (so
/// `quicktype` names types from the key, not the referencing property),
/// and `schema_version`'s integer `const` is dropped (`quicktype` chokes
/// on a numeric `const` — `s.codePointAt is not a function`); the precise
/// committed schemas keep the `const`.
fn write_combined_schema(root: &Path) -> Result<PathBuf, String> {
    let mut defs = Map::new();
    let mut props = Map::new();
    for (rel, _) in SCHEMA_FILES {
        let path = root.join(rel);
        let text =
            fs::read_to_string(&path).map_err(|err| format!("read {}: {err}", path.display()))?;
        let schema: Value = serde_json::from_str(&text)
            .map_err(|err| format!("parse {}: {err}", path.display()))?;
        let obj = schema
            .as_object()
            .ok_or_else(|| format!("{}: schema root is not an object", path.display()))?;
        let env_title = obj
            .get("title")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("{}: schema missing root title", path.display()))?
            .to_owned();
        // Shared sub-types (SpanWire / OffsetWire), hoisted to root in the
        // committed schema — merge, first definition wins (they're identical).
        if let Some(file_defs) = obj.get("$defs").and_then(Value::as_object) {
            for (key, value) in file_defs {
                defs.entry(key.clone()).or_insert_with(|| value.clone());
            }
        }
        // The per-entry item type (DiagnosticWire / NodeWire / …).
        let mut items = obj
            .get("properties")
            .and_then(|p| p.get("data"))
            .and_then(|d| d.get("items"))
            .cloned()
            .ok_or_else(|| format!("{}: missing properties.data.items", path.display()))?;
        let item_title = items
            .get("title")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("{}: data.items missing title", path.display()))?
            .to_owned();
        if let Some(item_obj) = items.as_object_mut() {
            item_obj.remove("$schema");
            item_obj.remove("$defs");
        }
        defs.insert(item_title.clone(), items);
        // The envelope type, referencing the item. `schema_version` is a
        // plain integer here (no `const`) for quicktype's sake.
        defs.insert(
            env_title.clone(),
            serde_json::json!({
                "type": "object",
                "additionalProperties": false,
                "required": ["schema_version", "data"],
                "properties": {
                    "schema_version": { "type": "integer" },
                    "data": { "type": "array", "items": { "$ref": format!("#/$defs/{item_title}") } },
                },
            }),
        );
        props.insert(
            env_title.clone(),
            serde_json::json!({ "$ref": format!("#/$defs/{env_title}") }),
        );
    }
    // Force quicktype to name every type from its `$defs` key by giving
    // each definition a matching `title`.
    for (key, value) in &mut defs {
        if let Some(value_obj) = value.as_object_mut() {
            value_obj.insert("title".to_owned(), Value::String(key.clone()));
        }
    }
    let combined = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "AozoraWire",
        "type": "object",
        "additionalProperties": false,
        "properties": props,
        "$defs": defs,
    });
    let combined_path = env::temp_dir().join("aozora_wire_combined.schema.json");
    let pretty = serde_json::to_string_pretty(&combined).map_err(|err| err.to_string())?;
    fs::write(&combined_path, pretty)
        .map_err(|err| format!("write combined schema {}: {err}", combined_path.display()))?;
    Ok(combined_path)
}

/// Run quicktype (+ gofmt for Go) over the combined schema and return the
/// finalized, header-stamped, trailing-whitespace-trimmed source.
fn generate_lang(lt: &LangType, combined_schema: &Path) -> Result<String, String> {
    let mut cmd = Command::new("quicktype");
    cmd.arg("--src-lang")
        .arg("schema")
        .arg("--lang")
        .arg(lt.quicktype_lang)
        .args(lt.extra)
        .arg(combined_schema);
    let output = cmd.output().map_err(|err| {
        format!(
            "failed to run quicktype ({err}); it ships in the dev image — \
             run via `just types-langs`, not on the host"
        )
    })?;
    if !output.status.success() {
        return Err(format!(
            "quicktype failed for `{}`:\n{}",
            lt.name,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let body = String::from_utf8(output.stdout)
        .map_err(|err| format!("quicktype output for `{}` not UTF-8: {err}", lt.name))?;
    // Assemble the complete file (header + prelude + body) first; gofmt
    // needs a whole Go file (with the `package` clause), not a fragment.
    let assembled = finalize(lt, &body);
    if lt.gofmt {
        gofmt(&assembled)
    } else {
        Ok(assembled)
    }
}

/// Pipe `src` through `gofmt -` so the committed Go artifact matches the
/// host package's own `gofmt` gate byte-for-byte.
fn gofmt(src: &str) -> Result<String, String> {
    use std::io::Write as _;
    use std::process::Stdio;

    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| format!("failed to run gofmt ({err}); it ships in the dev image"))?;
    child
        .stdin
        .take()
        .ok_or("gofmt: no stdin handle")?
        .write_all(src.as_bytes())
        .map_err(|err| format!("gofmt: write stdin: {err}"))?;
    let output = child
        .wait_with_output()
        .map_err(|err| format!("gofmt: wait: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "gofmt failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|err| format!("gofmt output not UTF-8: {err}"))
}

/// Prepend the generated-file header + optional prelude, and strip
/// trailing whitespace per line (quicktype's aligned comments otherwise
/// leave trailing spaces that would churn the drift gate).
fn finalize(lt: &LangType, body: &str) -> String {
    let mut out = String::new();
    out.push_str(lt.comment);
    out.push_str(
        "AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).\n",
    );
    out.push_str(lt.comment);
    out.push_str(
        "DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.\n",
    );
    out.push('\n');
    out.push_str(lt.prelude);
    for line in body.lines() {
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out
}
