#![expect(
    clippy::expect_used,
    reason = "type generation uses validated static regexes and schema structures"
)]

//! TypeScript types artefact dump / drift gate.
//!
//! Generates `crates/aozora-wasm/types/aozora_types.d.ts` for downstream
//! TypeScript consumers:
//!
//! ```text
//! import type { NodeKind, Diagnostic } from "aozora-wasm/aozora_types";
//! ```
//!
//! Two halves, anchored two different ways:
//!
//! * **Enums** (`NodeKind`, `PairKind`, …) are string-literal unions
//!   projected from the live `::ALL` constants — the JSON Schema erases
//!   them to a plain `string`, so they must come from Rust. Adding a
//!   variant flows into the output once the `ALL` array is updated.
//! * **Payload interfaces** (`Span`, `Diagnostic`, …) are hand-written:
//!   they carry `JSDoc` the schema has no field for, and `TextEdit` is an
//!   edit *input* with no wire schema at all. They are NOT free-floating —
//!   `xtask types check` cross-checks each interface's field set and
//!   optionality against the committed wire JSON Schema, which
//!   `xtask schema check` in turn ties to the live wire structs. A
//!   wire-struct field change therefore propagates schema → this parity
//!   check → a forced `.d.ts` edit.
//!
//! The source of truth lives outside `pkg/` because `wasm-pack`
//! wipes that directory on rebuild. A future packaging step copies
//! this file into `pkg/` before `npm publish`.
//!
//! Drift-gated by `xtask types check`: a stale artefact (the regen step
//! was forgotten) and an interface that disagrees with the schema both
//! fail CI.

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{Map, Value};

use std::fmt::Write as _;

use aozora::json::SCHEMA_VERSION;
use aozora::{ContainerKind, DiagnosticSource, InternalCheckCode, NodeKind, PairKind, Severity};

use crate::TypesArgs;
use crate::TypesOp;
use crate::schema::SCHEMA_FILES;

const TYPES_REL_PATH: &str = "crates/aozora-wasm/types/aozora_types.d.ts";
const C_HEADER_REL_PATH: &str = "crates/aozora-ffi/include/aozora.h";

pub(crate) fn dispatch(args: &TypesArgs) -> Result<(), String> {
    match args.op {
        TypesOp::Ts => dump(),
        TypesOp::Check => check(),
        TypesOp::Langs => langs_dump(),
        TypesOp::LangsCheck => langs_check(),
    }
}

fn workspace_root() -> Result<PathBuf, String> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let root = Path::new(manifest_dir)
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!("could not derive workspace root from CARGO_MANIFEST_DIR={manifest_dir:?}")
        })?;
    Ok(root.to_path_buf())
}

/// Render a Rust slice of enum variants into a TypeScript
/// string-literal union: `"a" | "b" | "c"`. Variants are projected
/// to their wire string via the supplied closure.
fn ts_string_union<T: Copy>(values: &[T], to_wire: impl Fn(T) -> &'static str) -> String {
    values
        .iter()
        .map(|v| format!("\"{}\"", to_wire(*v)))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Append `export type {name} = {union};` followed by a blank line.
/// Centralised here so `render_enums` stays free of `writeln!`-into-String
/// boilerplate (and the associated `let_underscore_must_use` clippy noise).
fn push_export_type(out: &mut String, name: &str, union: &str) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    out.push_str(union);
    out.push_str(";\n\n");
}

fn render() -> String {
    let mut out = String::new();
    render_header(&mut out);
    render_enums(&mut out);
    render_wire_payloads(&mut out);
    render_envelopes(&mut out);
    out
}

fn render_header(out: &mut String) {
    out.push_str("// AUTO-GENERATED by `xtask types ts` — DO NOT EDIT BY HAND.\n");
    out.push_str("// Regenerate with `just types` (or `xtask types ts`); commit the diff.\n");
    out.push_str("// Drift-gated in CI by `xtask types check`.\n");
    out.push('\n');
}

fn render_enums(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Enums (string-literal unions matching wire `kind` field)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Cross-cutting tag for an AST node or `NodeRef` projection. */\n");
    push_export_type(
        out,
        "NodeKind",
        &ts_string_union(&NodeKind::ALL, NodeKind::as_json_tag),
    );
    out.push_str("/** Pair kind for `pairs_json` output. */\n");
    push_export_type(
        out,
        "PairKind",
        &ts_string_union(PairKind::ALL, PairKind::as_json_tag),
    );
    out.push_str("/** Container kind for `container_pairs` output. */\n");
    push_export_type(
        out,
        "ContainerKind",
        &ts_string_union(&ContainerKind::ALL, ContainerKind::as_str),
    );
    out.push_str("/** Diagnostic severity tier (wire field `severity`). */\n");
    push_export_type(
        out,
        "Severity",
        &ts_string_union(&Severity::ALL, Severity::as_json_str),
    );
    out.push_str(
        "/** Diagnostic origin (wire field `source`). `internal` indicates a library bug. */\n",
    );
    push_export_type(
        out,
        "DiagnosticSource",
        &ts_string_union(&DiagnosticSource::ALL, DiagnosticSource::as_json_str),
    );
    out.push_str("/** Stable namespaced ID for an Internal sanity-check failure. */\n");
    push_export_type(
        out,
        "InternalCheckCode",
        &ts_string_union(&InternalCheckCode::ALL, InternalCheckCode::as_code),
    );
}

/// Render the wire payload interfaces (`Span`, `Diagnostic`, …). Hand-written
/// rather than projected from the schema so they can carry `JSDoc`;
/// [`check_payload_schema_parity`] guards that they stay field-for-field
/// consistent with the wire JSON Schema. `TextEdit` is an edit *input* with
/// no wire-output schema, so it lives here without a parity entry.
fn render_wire_payloads(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Wire envelope payload types\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str(
        "/** Half-open UTF-8 byte span `[start, end)` in original source coordinates. */\n",
    );
    out.push_str("export interface Span {\n  start: number;\n  end: number;\n}\n\n");
    out.push_str("/** One source edit in pre-edit UTF-8 byte coordinates. */\n");
    out.push_str(
        "export interface TextEdit {\n  start: number;\n  end: number;\n  replacement: string;\n}\n\n",
    );
    out.push_str("/** One entry of `diagnostics` — `Diagnostic` projection. */\n");
    out.push_str(
        "export interface Diagnostic {\n  /** Variant tag (last segment of `Diagnostic::code()`, e.g. `\"source_contains_pua\"`). */\n  kind: string;\n  severity: Severity;\n  source: DiagnosticSource;\n  span: Span;\n  /** Unicode scalar value (only `SourceContainsPua` carries one today). */\n  codepoint?: number;\n}\n\n",
    );
    out.push_str("/** One entry of `nodes` — classified `Node` span in source coords. */\n");
    out.push_str("export interface Node {\n  kind: NodeKind;\n  span: Span;\n}\n\n");
    out.push_str("/** One entry of `pairs` — matched bracket pair link. */\n");
    out.push_str(
        "export interface Pair {\n  kind: PairKind;\n  open: Span;\n  close: Span;\n}\n\n",
    );
    out.push_str(
        "/** One entry of `container_pairs` — paired container in source coordinates. */\n",
    );
    out.push_str(
        "export interface ContainerPair {\n  kind: ContainerKind;\n  open: Span;\n  close: Span;\n}\n\n",
    );
    out.push_str("/** One resolved `※［＃…］` reference. */\n");
    out.push_str(
        "export interface GaijiResolution {\n  span: Span;\n  description: string;\n  mencode?: string;\n  codepoint?: number;\n  resolved?: string;\n}\n\n",
    );
    out.push_str("/** One completion-catalogue entry. */\n");
    out.push_str(
        "export interface Slug {\n  canonical: string;\n  family: string;\n  accepts_param: boolean;\n  doc: string;\n  partner?: string;\n}\n\n",
    );
}

fn render_envelopes(out: &mut String) {
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push_str("// Envelopes (top-level shape returned by every wire endpoint)\n");
    out.push_str("// ─────────────────────────────────────────────────────────\n");
    out.push('\n');
    out.push_str("/** Generic wire envelope. Every endpoint emits this top-level shape. */\n");
    write!(
        out,
        "export interface JsonEnvelope<T> {{\n  schemaVersion: {SCHEMA_VERSION};\n  data: ReadonlyArray<T>;\n}}\n\n",
    )
    .expect("writing to a String is infallible");
    out.push_str("export type DiagnosticsEnvelope    = JsonEnvelope<Diagnostic>;\n");
    out.push_str("export type NodesEnvelope          = JsonEnvelope<Node>;\n");
    out.push_str("export type PairsEnvelope          = JsonEnvelope<Pair>;\n");
    out.push_str("export type ContainerPairsEnvelope = JsonEnvelope<ContainerPair>;\n");
    out.push_str("export type GaijiEnvelope          = JsonEnvelope<GaijiResolution>;\n");
    out.push_str("export type SlugsEnvelope           = JsonEnvelope<Slug>;\n");
}

fn dump() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
    }
    fs::write(&path, render())
        .map_err(|err| format!("write types artefact {}: {err}", path.display()))?;
    eprintln!("xtask types ts: wrote {}", path.display());
    Ok(())
}

fn check() -> Result<(), String> {
    let root = workspace_root()?;
    let path = root.join(TYPES_REL_PATH);
    let actual = render();
    let stored = fs::read_to_string(&path)
        .map_err(|err| format!("read types artefact {}: {err}", path.display()))?;
    let mut errors = Vec::new();
    if actual != stored {
        errors.push(format!(
            "TypeScript types drift detected in {TYPES_REL_PATH}: \
             run `xtask types ts` to regenerate, then commit"
        ));
    }
    // Anchor the hand-written payload interfaces to the wire JSON Schema, so a
    // wire-struct field change cannot slip past the byte-identical drift check
    // (both sides share the same hand-written strings).
    if let Err(err) = check_payload_schema_parity(&root, &actual) {
        errors.push(err);
    }
    if errors.is_empty() {
        eprintln!("xtask types check: aozora_types.d.ts up to date and schema-consistent");
        Ok(())
    } else {
        Err(errors.join("\n"))
    }
}

/// One payload type's field shape from the wire JSON Schema.
struct SchemaFields {
    /// All property names.
    properties: BTreeSet<String>,
    /// The subset marked `required`; everything else is optional.
    required: BTreeSet<String>,
}

/// Field shapes for every payload type the committed wire schemas define,
/// keyed by type title (`Diagnostic`, `Node`, `Span`, …). Built from the same
/// `SCHEMA_FILES` the host-language types are generated from; `xtask schema
/// check` ties those to the live wire structs, so this is the anchor the
/// hand-written `.d.ts` interfaces are checked against.
fn schema_field_shapes(root: &Path) -> Result<BTreeMap<String, SchemaFields>, String> {
    let mut shapes = BTreeMap::new();
    for (rel, _) in SCHEMA_FILES {
        let path = root.join(rel);
        let text =
            fs::read_to_string(&path).map_err(|err| format!("read {}: {err}", path.display()))?;
        let schema: Value = serde_json::from_str(&text)
            .map_err(|err| format!("parse {}: {err}", path.display()))?;
        // The per-entry item type (Diagnostic / Node / …) — named by its title.
        if let Some(items) = schema
            .get("properties")
            .and_then(|p| p.get("data"))
            .and_then(|d| d.get("items"))
            && let Some(title) = items.get("title").and_then(Value::as_str)
        {
            insert_object_shape(title, items, &mut shapes);
        }
        // Shared `$defs` (Span, …) are named by their key, not an inner title;
        // identical across files, so first wins.
        if let Some(defs) = schema.get("$defs").and_then(Value::as_object) {
            for (key, def) in defs {
                insert_object_shape(key, def, &mut shapes);
            }
        }
    }
    Ok(shapes)
}

/// Record `obj`'s `properties` + `required` under `name`, if it is an object
/// schema with properties. First insertion wins (shared `$defs` repeat
/// identically across files).
fn insert_object_shape(name: &str, obj: &Value, shapes: &mut BTreeMap<String, SchemaFields>) {
    let Some(props) = obj.get("properties").and_then(Value::as_object) else {
        return;
    };
    let properties = props.keys().cloned().collect();
    let required = obj
        .get("required")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default();
    shapes.entry(name.to_owned()).or_insert(SchemaFields {
        properties,
        required,
    });
}

/// The fields of one generated `export interface`: name → is-optional
/// (`field?:`). `None` if the interface is absent from the artefact.
fn dts_interface_fields(dts: &str, name: &str) -> Option<BTreeMap<String, bool>> {
    let header = format!("export interface {name} {{");
    let after = &dts[dts.find(&header)? + header.len()..];
    let body = &after[..after.find("\n}")?];
    let mut fields = BTreeMap::new();
    for line in body.lines() {
        let line = line.trim();
        // Skip blank lines and JSDoc (`/** … */`, ` * …`).
        if line.is_empty() || line.starts_with('/') || line.starts_with('*') {
            continue;
        }
        let Some(colon) = line.find(':') else {
            continue;
        };
        let key = line[..colon].trim();
        let (key, optional) = key
            .strip_suffix('?')
            .map_or((key, false), |base| (base, true));
        if !key.is_empty() && key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            fields.insert(key.to_owned(), optional);
        }
    }
    Some(fields)
}

/// Interfaces that mirror a wire schema type, and the schema title each must
/// match. `TextEdit` is deliberately absent — an edit *input* with no
/// wire-output schema — so it is exempt from this parity check.
const SCHEMA_MIRRORED_INTERFACES: &[(&str, &str)] = &[
    ("Span", "Span"),
    ("Diagnostic", "Diagnostic"),
    ("Node", "Node"),
    ("Pair", "Pair"),
    ("ContainerPair", "ContainerPair"),
    ("GaijiResolution", "GaijiResolution"),
    ("Slug", "Slug"),
];

/// Cross-check every schema-backed `.d.ts` payload interface against the wire
/// JSON Schema: same field names, and `?` iff the field is not
/// schema-`required`. This is what the byte-identical drift check alone cannot
/// do — `render()` and the committed artefact share the same hand-written
/// strings, so a wire field added in Rust (which reaches the schema via
/// `xtask schema check`) would otherwise never surface as a `.d.ts` gap.
fn check_payload_schema_parity(root: &Path, dts: &str) -> Result<(), String> {
    let shapes = schema_field_shapes(root)?;
    let mut problems = Vec::new();
    for (interface, title) in SCHEMA_MIRRORED_INTERFACES {
        let Some(shape) = shapes.get(*title) else {
            problems.push(format!(
                "no wire schema defines `{title}` to check interface `{interface}` against"
            ));
            continue;
        };
        let Some(fields) = dts_interface_fields(dts, interface) else {
            problems.push(format!("generated .d.ts has no `interface {interface}`"));
            continue;
        };
        let names: BTreeSet<String> = fields.keys().cloned().collect();
        for missing in shape.properties.difference(&names) {
            problems.push(format!(
                "interface `{interface}` is missing wire field `{missing}` (the schema has it)"
            ));
        }
        for extra in names.difference(&shape.properties) {
            problems.push(format!(
                "interface `{interface}` declares field `{extra}` absent from the schema"
            ));
        }
        for (field, &optional) in &fields {
            if !shape.properties.contains(field) {
                continue;
            }
            // Mismatch iff the two notions of "optional" disagree: a field is
            // consistent when `optional` (TS `?`) equals "not schema-required".
            if optional == shape.required.contains(field) {
                problems.push(format!(
                    "interface `{interface}` field `{field}` is {} but the schema marks it {}",
                    if optional {
                        "optional (`?`)"
                    } else {
                        "required"
                    },
                    if shape.required.contains(field) {
                        "required"
                    } else {
                        "optional"
                    },
                ));
            }
        }
    }
    if problems.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "TypeScript payload interfaces disagree with the wire JSON Schema:\n  {}\n  \
             -> if the schema is right (run `xtask schema check`), edit the interface in \
             `render_wire_payloads` to match",
            problems.join("\n  "),
        ))
    }
}

// ────────────────────────────────────────────────────────────────────
// Per-language wire types via quicktype (`xtask types langs`)
// ────────────────────────────────────────────────────────────────────
//
// The TypeScript `.d.ts` above is hand-rolled from the live Rust enums
// (it needs the string-literal unions for `NodeKind` etc. that the JSON
// Schema erases to plain `string`). Every *other* host-SDK language is
// generated mechanically by `quicktype` from the committed JSON
// Schema — one generator, all languages — so adding a language is a
// single row in `LANG_TYPES`, not a new codegen backend.

/// One target language for `quicktype`-generated wire types.
struct LangType {
    /// Display name (and the key used in drift messages).
    name: &'static str,
    /// `quicktype --lang` identifier.
    quicktype_lang: &'static str,
    /// Output path, relative to the workspace root. Committed + drift-gated.
    out: &'static str,
    /// Line-comment prefix for the generated-file header.
    comment: &'static str,
    /// Text inserted between the header and the generated body — e.g. a
    /// Go `package` clause (quicktype's `--just-types` omits it).
    prelude: &'static str,
    /// Extra `quicktype` flags.
    extra: &'static [&'static str],
    /// When `true`, pipe the output through `gofmt` so the committed
    /// artifact matches what the host package's own `gofmt` gate expects.
    gofmt: bool,
}

/// The languages we generate wire types for. Adding a host SDK is one
/// row here plus a `crates/aozora-<lang>/` package that consumes the file.
const LANG_TYPES: &[LangType] = &[
    LangType {
        name: "go",
        quicktype_lang: "go",
        out: "crates/aozora-go/json_gen.go",
        comment: "// ",
        prelude: "package aozora\n\n",
        extra: &["--just-types", "--top-level", "AozoraJson"],
        gofmt: true,
    },
    LangType {
        name: "python",
        quicktype_lang: "py",
        out: "crates/aozora-py/python/aozora/wire_types.py",
        comment: "# ",
        prelude: "",
        extra: &["--python-version", "3.7", "--top-level", "AozoraJson"],
        gofmt: false,
    },
];

fn langs_dump() -> Result<(), String> {
    let root = workspace_root()?;
    let combined = write_combined_schema(&root)?;
    for lt in LANG_TYPES {
        let body = generate_lang(lt, &combined)?;
        let path = root.join(lt.out);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
        }
        fs::write(&path, &body)
            .map_err(|err| format!("write {} types {}: {err}", lt.name, path.display()))?;
        eprintln!("xtask types langs: wrote {}", path.display());
    }
    let header_path = root.join(C_HEADER_REL_PATH);
    if let Some(parent) = header_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create_dir_all {}: {err}", parent.display()))?;
    }
    fs::write(&header_path, generate_c_header(&root)?)
        .map_err(|err| format!("write C header {}: {err}", header_path.display()))?;
    eprintln!("xtask types langs: wrote {}", header_path.display());
    Ok(())
}

fn langs_check() -> Result<(), String> {
    let root = workspace_root()?;
    let combined = write_combined_schema(&root)?;
    let mut drift = Vec::new();
    for lt in LANG_TYPES {
        let actual = generate_lang(lt, &combined)?;
        let path = root.join(lt.out);
        let stored = fs::read_to_string(&path)
            .map_err(|err| format!("read {} types {}: {err}", lt.name, path.display()))?;
        if actual != stored {
            drift.push(lt.out.to_owned());
        }
    }
    let header_path = root.join(C_HEADER_REL_PATH);
    let actual = generate_c_header(&root)?;
    let stored = fs::read_to_string(&header_path)
        .map_err(|err| format!("read C header {}: {err}", header_path.display()))?;
    if actual != stored {
        drift.push(C_HEADER_REL_PATH.to_owned());
    }
    if drift.is_empty() {
        eprintln!("xtask types langs-check: generated host types and C header up to date");
        Ok(())
    } else {
        Err(format!(
            "per-language wire types drift detected in {} file(s):\n  {}\n\
             run `xtask types langs` to regenerate, then commit",
            drift.len(),
            drift.join("\n  "),
        ))
    }
}

/// Build one combined JSON Schema from the four committed per-envelope
/// schemas and write it to a temp file `quicktype` can consume. Returns
/// the temp path.
///
/// Why combine: feeding the four schema files to `quicktype` separately
/// makes it invent distinct names for the structurally-identical inner
/// types (`PurpleSpan`, `FluffySpan`, …). One document with a shared
/// `$defs` yields a single `Span`. Two transforms make
/// it digestible: every `$def` gets a `title` equal to its key (so
/// `quicktype` names types from the key, not the referencing property),
/// and `schemaVersion`'s integer `const` is dropped (`quicktype` chokes
/// on a numeric `const` — `s.codePointAt is not a function`); the precise
/// committed schemas keep the `const`.
fn write_combined_schema(root: &Path) -> Result<PathBuf, String> {
    let mut defs = Map::new();
    let mut props = Map::new();
    for (rel, _) in SCHEMA_FILES {
        let path = root.join(rel);
        let text =
            fs::read_to_string(&path).map_err(|err| format!("read {}: {err}", path.display()))?;
        let schema: Value = serde_json::from_str(&text)
            .map_err(|err| format!("parse {}: {err}", path.display()))?;
        let obj = schema
            .as_object()
            .ok_or_else(|| format!("{}: schema root is not an object", path.display()))?;
        let env_title = obj
            .get("title")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("{}: schema missing root title", path.display()))?
            .to_owned();
        // Shared span type, hoisted to root in the
        // committed schema — merge, first definition wins (they're identical).
        if let Some(file_defs) = obj.get("$defs").and_then(Value::as_object) {
            for (key, value) in file_defs {
                defs.entry(key.clone()).or_insert_with(|| value.clone());
            }
        }
        // The per-entry item type (Diagnostic / Node / …).
        let mut items = obj
            .get("properties")
            .and_then(|p| p.get("data"))
            .and_then(|d| d.get("items"))
            .cloned()
            .ok_or_else(|| format!("{}: missing properties.data.items", path.display()))?;
        let item_title = items
            .get("title")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("{}: data.items missing title", path.display()))?
            .to_owned();
        if let Some(item_obj) = items.as_object_mut() {
            item_obj.remove("$schema");
            item_obj.remove("$defs");
        }
        defs.insert(item_title.clone(), items);
        // The envelope type, referencing the item. `schemaVersion` is a
        // plain integer here (no `const`) for quicktype's sake.
        defs.insert(
            env_title.clone(),
            serde_json::json!({
                "type": "object",
                "additionalProperties": false,
                "required": ["schemaVersion", "data"],
                "properties": {
                    "schemaVersion": { "type": "integer" },
                    "data": { "type": "array", "items": { "$ref": format!("#/$defs/{item_title}") } },
                },
            }),
        );
        props.insert(
            env_title.clone(),
            serde_json::json!({ "$ref": format!("#/$defs/{env_title}") }),
        );
    }
    // Force quicktype to name every type from its `$defs` key by giving
    // each definition a matching `title`.
    for (key, value) in &mut defs {
        if let Some(value_obj) = value.as_object_mut() {
            value_obj.insert("title".to_owned(), Value::String(key.clone()));
        }
    }
    let combined = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "AozoraJson",
        "type": "object",
        "additionalProperties": false,
        "properties": props,
        "$defs": defs,
    });
    let combined_path = env::temp_dir().join("aozora_json_combined.schema.json");
    let pretty = serde_json::to_string_pretty(&combined).map_err(|err| err.to_string())?;
    fs::write(&combined_path, pretty)
        .map_err(|err| format!("write combined schema {}: {err}", combined_path.display()))?;
    Ok(combined_path)
}

/// Run quicktype (+ gofmt for Go) over the combined schema and return the
/// finalized, header-stamped, trailing-whitespace-trimmed source.
fn generate_lang(lt: &LangType, combined_schema: &Path) -> Result<String, String> {
    let mut cmd = Command::new("quicktype");
    cmd.arg("--src-lang")
        .arg("schema")
        .arg("--lang")
        .arg(lt.quicktype_lang)
        .args(lt.extra)
        .arg(combined_schema);
    let output = cmd.output().map_err(|err| {
        format!(
            "failed to run quicktype ({err}); run `just setup`, then \
             use `just types-langs`"
        )
    })?;
    if !output.status.success() {
        return Err(format!(
            "quicktype failed for `{}`:\n{}",
            lt.name,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let body = String::from_utf8(output.stdout)
        .map_err(|err| format!("quicktype output for `{}` not UTF-8: {err}", lt.name))?;
    // Assemble the complete file (header + prelude + body) first; gofmt
    // needs a whole Go file (with the `package` clause), not a fragment.
    let assembled = finalize(lt, &body);
    if lt.gofmt {
        gofmt(&assembled)
    } else if lt.name == "python" {
        strict_python(&assembled)
    } else {
        Ok(assembled)
    }
}

fn strict_python(source: &str) -> Result<String, String> {
    let import = "from typing import Any, List, Optional, TypeVar, Type, cast, Callable";
    let strict_import =
        "from typing import Any, Callable, Dict, List, Optional, Protocol, Type, TypeVar, cast";
    let to_class = "def to_class(c: Type[T], x: Any) -> dict:\n\
                    \x20   assert isinstance(x, c)\n\
                    \x20   return cast(Any, x).to_dict()";
    let strict_to_class = "class ToDict(Protocol):\n\
                           \x20   def to_dict(self) -> Dict[str, Any]: ...\n\
                           \n\
                           \n\
                           def to_class(c: Type[T], x: Any) -> Dict[str, Any]:\n\
                           \x20   assert isinstance(x, c)\n\
                           \x20   return cast(ToDict, x).to_dict()";
    let from_union = "def from_union(fs, x):\n\
                      \x20   for f in fs:\n\
                      \x20       try:\n\
                      \x20           return f(x)\n\
                      \x20       except:\n\
                      \x20           pass\n\
                      \x20   assert False";
    let strict_from_union = "def from_union(fs: List[Callable[[Any], Any]], x: Any) -> Any:\n\
         \x20   for f in fs:\n\
         \x20       try:\n\
         \x20           return f(x)\n\
         \x20       except (AssertionError, TypeError, ValueError):\n\
         \x20           pass\n\
         \x20   raise AssertionError";

    if !source.contains(import) || !source.contains(to_class) || !source.contains(from_union) {
        return Err("quicktype Python support prelude changed".to_owned());
    }
    Ok(source
        .replacen(import, strict_import, 1)
        .replacen(to_class, strict_to_class, 1)
        .replacen(from_union, strict_from_union, 1)
        .replace(" -> dict:", " -> Dict[str, Any]:")
        .replace("result: dict = {}", "result: Dict[str, Any] = {}"))
}

fn generate_c_header(root: &Path) -> Result<String, String> {
    let crate_dir = root.join("crates/aozora-ffi");
    let config = cbindgen::Config::from_file(crate_dir.join("cbindgen.toml"))
        .map_err(|err| format!("read cbindgen.toml: {err}"))?;
    let bindings = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_after_include(format!("#define AOZORA_SCHEMA_VERSION {SCHEMA_VERSION}"))
        .generate()
        .map_err(|err| format!("generate C header: {err}"))?;
    let mut bytes = Vec::new();
    bindings.write(&mut bytes);
    String::from_utf8(bytes).map_err(|err| format!("C header is not UTF-8: {err}"))
}

/// Pipe `src` through `gofmt -` so the committed Go artifact matches the
/// host package's own `gofmt` gate byte-for-byte.
fn gofmt(src: &str) -> Result<String, String> {
    use std::io::Write as _;
    use std::process::Stdio;

    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| format!("failed to run gofmt ({err}); run `just setup`"))?;
    child
        .stdin
        .take()
        .ok_or("gofmt: no stdin handle")?
        .write_all(src.as_bytes())
        .map_err(|err| format!("gofmt: write stdin: {err}"))?;
    let output = child
        .wait_with_output()
        .map_err(|err| format!("gofmt: wait: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "gofmt failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|err| format!("gofmt output not UTF-8: {err}"))
}

/// Prepend the generated-file header + optional prelude, and strip
/// trailing whitespace per line (quicktype's aligned comments otherwise
/// leave trailing spaces that would churn the drift gate).
fn finalize(lt: &LangType, body: &str) -> String {
    let mut out = String::new();
    out.push_str(lt.comment);
    out.push_str(
        "AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).\n",
    );
    out.push_str(lt.comment);
    out.push_str(
        "DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.\n",
    );
    out.push('\n');
    out.push_str(lt.prelude);
    if lt.name == "go" {
        writeln!(out, "const SchemaVersion = {SCHEMA_VERSION}\n")
            .expect("writing to a String is infallible");
    }
    for line in body.lines() {
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ts_string_union_joins_quoted_wire_strings() {
        let union = ts_string_union(&["a", "b", "c"], |s| s);
        assert_eq!(union, "\"a\" | \"b\" | \"c\"", "pipe-joined quoted union");
    }

    #[test]
    fn ts_string_union_single_value_has_no_pipe() {
        let union = ts_string_union(&["only"], |s| s);
        assert_eq!(union, "\"only\"", "single value: no separator");
    }

    #[test]
    fn push_export_type_emits_statement_and_blank_line() {
        let mut out = String::new();
        push_export_type(&mut out, "Foo", "\"x\" | \"y\"");
        assert_eq!(
            out, "export type Foo = \"x\" | \"y\";\n\n",
            "export type with trailing blank line"
        );
    }

    #[test]
    fn render_header_is_marked_auto_generated() {
        let mut out = String::new();
        render_header(&mut out);
        assert!(
            out.contains("AUTO-GENERATED"),
            "header must warn against hand edits: {out}"
        );
        assert!(
            out.contains("xtask types ts"),
            "header must name the regen command: {out}"
        );
    }

    #[test]
    fn render_enums_emits_every_live_enum_type() {
        let mut out = String::new();
        render_enums(&mut out);
        for name in [
            "NodeKind",
            "PairKind",
            "ContainerKind",
            "Severity",
            "DiagnosticSource",
            "InternalCheckCode",
        ] {
            assert!(
                out.contains(&format!("export type {name} =")),
                "missing `export type {name}`: {out}"
            );
        }
    }

    #[test]
    fn render_enums_projects_node_kind_via_camel_case() {
        let mut out = String::new();
        render_enums(&mut out);
        // `as_json_tag` projects Ruby → "ruby"; the union must carry it.
        assert!(
            out.contains("\"ruby\""),
            "NodeKind union must contain camelCase ruby: {out}"
        );
    }

    #[test]
    fn render_wire_payloads_defines_core_interfaces() {
        let mut out = String::new();
        render_wire_payloads(&mut out);
        for iface in [
            "interface Span",
            "interface Diagnostic",
            "interface Node",
            "interface Pair",
            "interface ContainerPair",
        ] {
            assert!(out.contains(iface), "missing `{iface}`: {out}");
        }
    }

    #[test]
    fn render_envelopes_aliases_each_endpoint() {
        let mut out = String::new();
        render_envelopes(&mut out);
        assert!(
            out.contains("interface JsonEnvelope<T>"),
            "generic envelope"
        );
        // The wire field is camelCase (the `Envelope` struct carries
        // `#[serde(rename_all = "camelCase")]`), so the generated `.d.ts`
        // must spell `schemaVersion`, not the Rust field name — a snake_case
        // spelling here once shipped a `.d.ts` that disagreed with runtime.
        assert!(
            out.contains(&format!("schemaVersion: {SCHEMA_VERSION};"))
                && !out.contains("schema_version"),
            "envelope field must be camelCase schemaVersion: {out}"
        );
        for alias in [
            "DiagnosticsEnvelope",
            "NodesEnvelope",
            "PairsEnvelope",
            "ContainerPairsEnvelope",
        ] {
            assert!(
                out.contains(alias),
                "missing envelope alias `{alias}`: {out}"
            );
        }
    }

    #[test]
    fn render_full_artefact_is_well_formed() {
        let dts = render();
        // Header first, enums + payloads + envelopes all present.
        assert!(dts.starts_with("// AUTO-GENERATED"), "header leads: {dts}");
        assert!(dts.contains("export type NodeKind ="), "enums section");
        assert!(dts.contains("interface Span"), "payload section");
        assert!(dts.contains("JsonEnvelope<Diagnostic>"), "envelope section");
    }

    #[test]
    fn dts_interface_fields_reads_names_and_optionality() {
        let dts = "export interface Diagnostic {\n  /** doc */\n  kind: string;\n  \
                   span: Span;\n  codepoint?: number;\n}\n";
        let fields = dts_interface_fields(dts, "Diagnostic").expect("interface present");
        assert_eq!(fields.get("kind"), Some(&false), "kind is required");
        assert_eq!(fields.get("span"), Some(&false), "span is required");
        assert_eq!(
            fields.get("codepoint"),
            Some(&true),
            "codepoint is optional"
        );
        assert_eq!(fields.len(), 3, "JSDoc lines are not fields: {fields:?}");
        assert!(
            dts_interface_fields(dts, "Absent").is_none(),
            "a missing interface reads as None"
        );
    }

    #[test]
    fn schema_field_shapes_cover_every_mirrored_interface() {
        let root = workspace_root().expect("workspace root");
        let shapes = schema_field_shapes(&root).expect("the committed schemas must parse");
        for (_, title) in SCHEMA_MIRRORED_INTERFACES {
            assert!(
                shapes.contains_key(*title),
                "schema shape for `{title}` must exist (mirrored interface has no anchor)"
            );
        }
    }

    #[test]
    fn live_payload_interfaces_match_the_schema() {
        // The integration guard: the hand-written interfaces the artefact
        // ships must agree, field-for-field, with the committed wire schema.
        let root = workspace_root().expect("workspace root");
        check_payload_schema_parity(&root, &render())
            .expect("hand-written .d.ts interfaces must match the wire schema");
    }

    #[test]
    fn parity_flags_an_interface_missing_a_wire_field() {
        let root = workspace_root().expect("workspace root");
        // Drop `severity` (unique to Diagnostic) from an otherwise-live artefact.
        let doctored = render().replace("  severity: Severity;\n", "");
        let err = check_payload_schema_parity(&root, &doctored)
            .expect_err("a dropped wire field must be flagged");
        assert!(
            err.contains("Diagnostic") && err.contains("severity") && err.contains("missing"),
            "must name the interface and missing field: {err}"
        );
    }

    #[test]
    fn parity_flags_a_wrong_optionality() {
        let root = workspace_root().expect("workspace root");
        // Make required `kind` optional in the Node interface.
        let doctored = render().replace(
            "export interface Node {\n  kind: NodeKind;",
            "export interface Node {\n  kind?: NodeKind;",
        );
        let err = check_payload_schema_parity(&root, &doctored)
            .expect_err("wrong optionality must be flagged");
        assert!(
            err.contains("Node") && err.contains("kind") && err.contains("required"),
            "must name the interface, field, and the schema's requirement: {err}"
        );
    }

    #[test]
    fn finalize_prepends_header_and_prelude() {
        let lt = &LANG_TYPES[0];
        let out = finalize(lt, "type X struct{}\n");
        assert!(out.contains("AUTO-GENERATED"), "header present: {out}");
        assert!(out.contains("package aozora"), "Go prelude present: {out}");
        assert!(out.contains("type X struct{}"), "body present: {out}");
    }

    #[test]
    fn finalize_trims_trailing_whitespace_per_line() {
        let lt = &LANG_TYPES[0];
        let out = finalize(lt, "a   \nb\t\n");
        // Every line of the assembled output must be free of trailing space.
        for line in out.lines() {
            assert_eq!(
                line.trim_end(),
                line,
                "line has trailing whitespace: {line:?}"
            );
        }
        assert!(out.contains("\na\n"), "trimmed body line `a`: {out}");
        assert!(out.contains("\nb\n"), "trimmed body line `b`: {out}");
    }
}
