# Type stub for the compiled extension submodule `aozora._aozora`.
#
# Hand-written: a `.so` cannot be introspected by type checkers, so the
# native surface is declared here. The PUBLIC API users import from
# `aozora` (the pure-Python wrapper in __init__.py, which is itself
# fully annotated) — this stub only types the private submodule so mypy
# can check the wrapper and power users who reach into `_aozora`
# still get hints.
#
# Keep in sync with `crates/aozora-py/src/lib.rs`. The drift guard in
# `tests/test_typing.py` asserts every symbol declared here exists on
# the runtime module.

class Document:
    def __init__(self, source: str) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> Document: ...
    @property
    def source(self) -> str: ...
    def source_byte_len(self) -> int: ...
    def to_html(self) -> str: ...
    def to_source(self) -> str: ...
    def diagnostics_json(self) -> str: ...
    def nodes_json(self) -> str: ...
    def pairs_json(self) -> str: ...
    def container_pairs_json(self) -> str: ...
    def gaiji_json(self) -> str: ...

def parse_to_html(source: str) -> str: ...
def prewarm() -> None: ...
def decode_sjis(data: bytes) -> str: ...
def slugs_json() -> str: ...
