# AUTO-GENERATED by `xtask types langs` (quicktype, from the aozora wire JSON Schema).
# DO NOT EDIT — regenerate with `just types-langs`; drift-gated by `just drift-gate`.

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Protocol, Type, TypeVar, cast


T = TypeVar("T")


def from_int(x: Any) -> int:
    assert isinstance(x, int) and not isinstance(x, bool)
    return x


def from_str(x: Any) -> str:
    assert isinstance(x, str)
    return x


class ToDict(Protocol):
    def to_dict(self) -> Dict[str, Any]: ...


def to_class(c: Type[T], x: Any) -> Dict[str, Any]:
    assert isinstance(x, c)
    return cast(ToDict, x).to_dict()


def from_list(f: Callable[[Any], T], x: Any) -> List[T]:
    assert isinstance(x, list)
    return [f(y) for y in x]


def from_none(x: Any) -> Any:
    assert x is None
    return x


def from_union(fs: List[Callable[[Any], Any]], x: Any) -> Any:
    for f in fs:
        try:
            return f(x)
        except (AssertionError, TypeError, ValueError):
            pass
    raise AssertionError


def from_bool(x: Any) -> bool:
    assert isinstance(x, bool)
    return x


@dataclass
class Span:
    """One half-open `[start, end)` byte span in a wire envelope."""

    end: int
    start: int

    @staticmethod
    def from_dict(obj: Any) -> 'Span':
        assert isinstance(obj, dict)
        end = from_int(obj.get("end"))
        start = from_int(obj.get("start"))
        return Span(end, start)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["end"] = from_int(self.end)
        result["start"] = from_int(self.start)
        return result


@dataclass
class ContainerPair:
    """One `container_pairs` envelope entry."""

    close: Span
    kind: str
    open: Span

    @staticmethod
    def from_dict(obj: Any) -> 'ContainerPair':
        assert isinstance(obj, dict)
        close = Span.from_dict(obj.get("close"))
        kind = from_str(obj.get("kind"))
        open = Span.from_dict(obj.get("open"))
        return ContainerPair(close, kind, open)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["close"] = to_class(Span, self.close)
        result["kind"] = from_str(self.kind)
        result["open"] = to_class(Span, self.open)
        return result


@dataclass
class AozoraContainerPairsEnvelope:
    data: List[ContainerPair]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraContainerPairsEnvelope':
        assert isinstance(obj, dict)
        data = from_list(ContainerPair.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraContainerPairsEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(ContainerPair, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class Diagnostic:
    """One `diagnostics` envelope entry — a projected [`crate::Diagnostic`]."""

    kind: str
    severity: str
    source: str
    span: Span
    codepoint: Optional[int] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Diagnostic':
        assert isinstance(obj, dict)
        kind = from_str(obj.get("kind"))
        severity = from_str(obj.get("severity"))
        source = from_str(obj.get("source"))
        span = Span.from_dict(obj.get("span"))
        codepoint = from_union([from_none, from_int], obj.get("codepoint"))
        return Diagnostic(kind, severity, source, span, codepoint)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["kind"] = from_str(self.kind)
        result["severity"] = from_str(self.severity)
        result["source"] = from_str(self.source)
        result["span"] = to_class(Span, self.span)
        if self.codepoint is not None:
            result["codepoint"] = from_union([from_none, from_int], self.codepoint)
        return result


@dataclass
class AozoraDiagnosticsEnvelope:
    data: List[Diagnostic]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraDiagnosticsEnvelope':
        assert isinstance(obj, dict)
        data = from_list(Diagnostic.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraDiagnosticsEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(Diagnostic, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class GaijiResolution:
    """One `gaiji` envelope entry — a resolved `※［＃…］` reference."""

    description: str
    span: Span
    codepoint: Optional[int] = None
    mencode: Optional[str] = None
    resolved: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> 'GaijiResolution':
        assert isinstance(obj, dict)
        description = from_str(obj.get("description"))
        span = Span.from_dict(obj.get("span"))
        codepoint = from_union([from_none, from_int], obj.get("codepoint"))
        mencode = from_union([from_none, from_str], obj.get("mencode"))
        resolved = from_union([from_none, from_str], obj.get("resolved"))
        return GaijiResolution(description, span, codepoint, mencode, resolved)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["description"] = from_str(self.description)
        result["span"] = to_class(Span, self.span)
        if self.codepoint is not None:
            result["codepoint"] = from_union([from_none, from_int], self.codepoint)
        if self.mencode is not None:
            result["mencode"] = from_union([from_none, from_str], self.mencode)
        if self.resolved is not None:
            result["resolved"] = from_union([from_none, from_str], self.resolved)
        return result


@dataclass
class AozoraGaijiEnvelope:
    data: List[GaijiResolution]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraGaijiEnvelope':
        assert isinstance(obj, dict)
        data = from_list(GaijiResolution.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraGaijiEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(GaijiResolution, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class Node:
    """One `nodes` envelope entry — a classified node span in source coords."""

    kind: str
    span: Span

    @staticmethod
    def from_dict(obj: Any) -> 'Node':
        assert isinstance(obj, dict)
        kind = from_str(obj.get("kind"))
        span = Span.from_dict(obj.get("span"))
        return Node(kind, span)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["kind"] = from_str(self.kind)
        result["span"] = to_class(Span, self.span)
        return result


@dataclass
class AozoraNodesEnvelope:
    data: List[Node]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraNodesEnvelope':
        assert isinstance(obj, dict)
        data = from_list(Node.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraNodesEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(Node, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class Pair:
    """One `pairs` envelope entry — a matched bracket pair."""

    close: Span
    kind: str
    open: Span

    @staticmethod
    def from_dict(obj: Any) -> 'Pair':
        assert isinstance(obj, dict)
        close = Span.from_dict(obj.get("close"))
        kind = from_str(obj.get("kind"))
        open = Span.from_dict(obj.get("open"))
        return Pair(close, kind, open)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["close"] = to_class(Span, self.close)
        result["kind"] = from_str(self.kind)
        result["open"] = to_class(Span, self.open)
        return result


@dataclass
class AozoraPairsEnvelope:
    data: List[Pair]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraPairsEnvelope':
        assert isinstance(obj, dict)
        data = from_list(Pair.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraPairsEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(Pair, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class Slug:
    """One `slugs` envelope entry — a row of the annotation slug catalogue."""

    accepts_param: bool
    canonical: str
    doc: str
    family: str
    partner: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Slug':
        assert isinstance(obj, dict)
        accepts_param = from_bool(obj.get("accepts_param"))
        canonical = from_str(obj.get("canonical"))
        doc = from_str(obj.get("doc"))
        family = from_str(obj.get("family"))
        partner = from_union([from_none, from_str], obj.get("partner"))
        return Slug(accepts_param, canonical, doc, family, partner)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["accepts_param"] = from_bool(self.accepts_param)
        result["canonical"] = from_str(self.canonical)
        result["doc"] = from_str(self.doc)
        result["family"] = from_str(self.family)
        if self.partner is not None:
            result["partner"] = from_union([from_none, from_str], self.partner)
        return result


@dataclass
class AozoraSlugsEnvelope:
    data: List[Slug]
    schema_version: int

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraSlugsEnvelope':
        assert isinstance(obj, dict)
        data = from_list(Slug.from_dict, obj.get("data"))
        schema_version = from_int(obj.get("schemaVersion"))
        return AozoraSlugsEnvelope(data, schema_version)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        result["data"] = from_list(lambda x: to_class(Slug, x), self.data)
        result["schemaVersion"] = from_int(self.schema_version)
        return result


@dataclass
class AozoraJSON:
    aozora_container_pairs_envelope: Optional[AozoraContainerPairsEnvelope] = None
    aozora_diagnostics_envelope: Optional[AozoraDiagnosticsEnvelope] = None
    aozora_gaiji_envelope: Optional[AozoraGaijiEnvelope] = None
    aozora_nodes_envelope: Optional[AozoraNodesEnvelope] = None
    aozora_pairs_envelope: Optional[AozoraPairsEnvelope] = None
    aozora_slugs_envelope: Optional[AozoraSlugsEnvelope] = None

    @staticmethod
    def from_dict(obj: Any) -> 'AozoraJSON':
        assert isinstance(obj, dict)
        aozora_container_pairs_envelope = from_union([AozoraContainerPairsEnvelope.from_dict, from_none], obj.get("AozoraContainerPairsEnvelope"))
        aozora_diagnostics_envelope = from_union([AozoraDiagnosticsEnvelope.from_dict, from_none], obj.get("AozoraDiagnosticsEnvelope"))
        aozora_gaiji_envelope = from_union([AozoraGaijiEnvelope.from_dict, from_none], obj.get("AozoraGaijiEnvelope"))
        aozora_nodes_envelope = from_union([AozoraNodesEnvelope.from_dict, from_none], obj.get("AozoraNodesEnvelope"))
        aozora_pairs_envelope = from_union([AozoraPairsEnvelope.from_dict, from_none], obj.get("AozoraPairsEnvelope"))
        aozora_slugs_envelope = from_union([AozoraSlugsEnvelope.from_dict, from_none], obj.get("AozoraSlugsEnvelope"))
        return AozoraJSON(aozora_container_pairs_envelope, aozora_diagnostics_envelope, aozora_gaiji_envelope, aozora_nodes_envelope, aozora_pairs_envelope, aozora_slugs_envelope)

    def to_dict(self) -> Dict[str, Any]:
        result: Dict[str, Any] = {}
        if self.aozora_container_pairs_envelope is not None:
            result["AozoraContainerPairsEnvelope"] = from_union([lambda x: to_class(AozoraContainerPairsEnvelope, x), from_none], self.aozora_container_pairs_envelope)
        if self.aozora_diagnostics_envelope is not None:
            result["AozoraDiagnosticsEnvelope"] = from_union([lambda x: to_class(AozoraDiagnosticsEnvelope, x), from_none], self.aozora_diagnostics_envelope)
        if self.aozora_gaiji_envelope is not None:
            result["AozoraGaijiEnvelope"] = from_union([lambda x: to_class(AozoraGaijiEnvelope, x), from_none], self.aozora_gaiji_envelope)
        if self.aozora_nodes_envelope is not None:
            result["AozoraNodesEnvelope"] = from_union([lambda x: to_class(AozoraNodesEnvelope, x), from_none], self.aozora_nodes_envelope)
        if self.aozora_pairs_envelope is not None:
            result["AozoraPairsEnvelope"] = from_union([lambda x: to_class(AozoraPairsEnvelope, x), from_none], self.aozora_pairs_envelope)
        if self.aozora_slugs_envelope is not None:
            result["AozoraSlugsEnvelope"] = from_union([lambda x: to_class(AozoraSlugsEnvelope, x), from_none], self.aozora_slugs_envelope)
        return result


def aozora_json_from_dict(s: Any) -> AozoraJSON:
    return AozoraJSON.from_dict(s)


def aozora_json_to_dict(x: AozoraJSON) -> Any:
    return to_class(AozoraJSON, x)
