// AUTO-GENERATED by `xtask types ts` — DO NOT EDIT BY HAND.
// Regenerate with `just types-ts` (or `xtask types ts`); commit the diff.
// Drift-gated in CI by `xtask types check`.

// ─────────────────────────────────────────────────────────
// Enums (string-literal unions matching wire `kind` field)
// ─────────────────────────────────────────────────────────

/** Cross-cutting tag for an AST node or `NodeRef` projection. */
export type NodeKind = "ruby" | "bouten" | "combineUpright" | "gaiji" | "indent" | "alignEnd" | "center" | "warichu" | "framed" | "pageBreak" | "sectionBreak" | "heading" | "headingHint" | "illustration" | "kaeriten" | "directive" | "angleQuote" | "emphasis" | "marginNote" | "container" | "containerOpen" | "containerClose";

/** Pair kind for `pairs_json` output. */
export type PairKind = "bracket" | "ruby" | "angleQuote" | "tortoise" | "quote";

/** Container kind for `container_pairs` output. */
export type ContainerKind = "indent" | "warichu" | "framed" | "alignEnd" | "lineWidth" | "boutenRange" | "bold" | "italic" | "heading" | "columns" | "table" | "horizontal" | "fontSize" | "smallScript" | "caption" | "combineUprightRange";

/** Diagnostic severity tier (wire field `severity`). */
export type Severity = "error" | "warning" | "note";

/** Diagnostic origin (wire field `source`). `internal` indicates a library bug. */
export type DiagnosticSource = "source" | "internal";

/** Stable namespaced ID for an Internal sanity-check failure. */
export type InternalCheckCode = "aozora::lex::residual_annotation_marker" | "aozora::lex::unregistered_sentinel" | "aozora::lex::registry_out_of_order" | "aozora::lex::registry_position_mismatch";

/** PUA sentinel codepoint kind (4 reserved markers in `U+E001..U+E004`). */
export type SentinelKind = "inline" | "blockLeaf" | "blockOpen" | "blockClose";

// ─────────────────────────────────────────────────────────
// Wire envelope payload types
// ─────────────────────────────────────────────────────────

/** Half-open byte span `[start, end)` in the relevant coordinate system
(sanitized source for diagnostics / nodes / pairs; see `aozora::json` docs). */
export interface Span {
  start: number;
  end: number;
}

/** Single byte offset (used by `ContainerPair` open / close in normalized coords). */
export interface Offset {
  offset: number;
}

/** One entry of `diagnostics` — `Diagnostic` projection. */
export interface Diagnostic {
  /** Variant tag (last segment of `Diagnostic::code()`, e.g. `"source_contains_pua"`). */
  kind: string;
  severity: Severity;
  source: DiagnosticSource;
  span: Span;
  /** Codepoint payload (only `SourceContainsPua` carries one today). */
  codepoint?: string;
}

/** One entry of `nodes` — classified `Node` span in source coords. */
export interface Node {
  kind: NodeKind;
  span: Span;
}

/** One entry of `pairs` — matched bracket pair link. */
export interface Pair {
  kind: PairKind;
  open: Span;
  close: Span;
}

/** One entry of `container_pairs` — paired container (open in normalized coords). */
export interface ContainerPair {
  kind: ContainerKind;
  open: Offset;
  close: Offset;
}

// ─────────────────────────────────────────────────────────
// Envelopes (top-level shape returned by every wire endpoint)
// ─────────────────────────────────────────────────────────

/** Generic wire envelope. Every endpoint emits this top-level shape. */
export interface JsonEnvelope<T> {
  schema_version: 1;
  data: ReadonlyArray<T>;
}

export type DiagnosticsEnvelope    = JsonEnvelope<Diagnostic>;
export type NodesEnvelope          = JsonEnvelope<Node>;
export type PairsEnvelope          = JsonEnvelope<Pair>;
export type ContainerPairsEnvelope = JsonEnvelope<ContainerPair>;
