// AUTO-GENERATED by `xtask types ts` — DO NOT EDIT BY HAND.
// Regenerate with `just types-ts` (or `xtask types ts`); commit the diff.
// Drift-gated in CI by `xtask types check`.

// ─────────────────────────────────────────────────────────
// Enums (string-literal unions matching wire `kind` field)
// ─────────────────────────────────────────────────────────

/** Cross-cutting tag for an AST node or `NodeRef` projection. */
export type NodeKind = "ruby" | "bouten" | "tateChuYoko" | "gaiji" | "indent" | "alignEnd" | "warichu" | "keigakomi" | "pageBreak" | "sectionBreak" | "heading" | "headingHint" | "sashie" | "kaeriten" | "annotation" | "doubleRuby" | "container" | "containerOpen" | "containerClose";

/** Pair kind for `pairs_json` output. */
export type PairKind = "bracket" | "ruby" | "doubleRuby" | "tortoise" | "quote";

/** Diagnostic severity tier (wire field `severity`). */
export type Severity = "error" | "warning" | "note";

/** Diagnostic origin (wire field `source`). `internal` indicates a library bug. */
export type DiagnosticSource = "source" | "internal";

/** Stable namespaced ID for an Internal sanity-check failure. */
export type InternalCheckCode = "aozora::lex::residual_annotation_marker" | "aozora::lex::unregistered_sentinel" | "aozora::lex::registry_out_of_order" | "aozora::lex::registry_position_mismatch";

/** PUA sentinel codepoint kind (4 reserved markers in `U+E001..U+E004`). */
export type SentinelKind = "inline" | "blockLeaf" | "blockOpen" | "blockClose";

// ─────────────────────────────────────────────────────────
// Wire envelope payload types
// ─────────────────────────────────────────────────────────

/** Half-open byte span `[start, end)` in the relevant coordinate system
(sanitized source for diagnostics / nodes / pairs; see `aozora::wire` docs). */
export interface SpanWire {
  start: number;
  end: number;
}

/** Single byte offset (used by `ContainerPairWire` open / close in normalized coords). */
export interface OffsetWire {
  offset: number;
}

/** One entry of `serialize_diagnostics` — `Diagnostic` projection. */
export interface DiagnosticWire {
  /** Variant tag (last segment of `Diagnostic::code()`, e.g. `"source_contains_pua"`). */
  kind: string;
  severity: Severity;
  source: DiagnosticSource;
  span: SpanWire;
  /** Codepoint payload (only `SourceContainsPua` carries one today). */
  codepoint?: string;
}

/** One entry of `serialize_nodes` — classified `AozoraNode` span in source coords. */
export interface NodeWire {
  kind: NodeKind;
  span: SpanWire;
}

/** One entry of `serialize_pairs` — matched bracket pair link. */
export interface PairWire {
  kind: PairKind;
  open: SpanWire;
  close: SpanWire;
}

/** One entry of `serialize_container_pairs` — paired container (open in normalized coords). */
export interface ContainerPairWire {
  kind: "indent" | "warichu" | "keigakomi" | "alignEnd" | "unknown";
  open: OffsetWire;
  close: OffsetWire;
}

// ─────────────────────────────────────────────────────────
// Envelopes (top-level shape returned by every wire endpoint)
// ─────────────────────────────────────────────────────────

/** Generic wire envelope. Every endpoint emits this top-level shape. */
export interface WireEnvelope<T> {
  schema_version: 1;
  data: ReadonlyArray<T>;
}

export type DiagnosticsEnvelope    = WireEnvelope<DiagnosticWire>;
export type NodesEnvelope          = WireEnvelope<NodeWire>;
export type PairsEnvelope          = WireEnvelope<PairWire>;
export type ContainerPairsEnvelope = WireEnvelope<ContainerPairWire>;
