/*
 * End-to-end C ABI smoke test for aozora-ffi.
 *
 * This program is the reference C consumer of the public surface
 * exposed by `crates/aozora-ffi/src/lib.rs`. It exercises every
 * `aozora_*` function on the happy path:
 *
 *   1. aozora_document_new            — construct from bytes
 *   2. aozora_document_to_html        — render HTML
 *   3. aozora_document_to_source      — round-trip source re-emission
 *   4. aozora_document_diagnostics_json — diagnostic projection
 *   5. aozora_document_diagnostics_text — plain-text diagnostics
 *   6. aozora_document_nodes_json     — source-keyed node projection
 *   7. aozora_document_pairs_json     — inline open/close pair links
 *   8. aozora_document_container_pairs_json — block enclosure pairs
 *   9. aozora_document_gaiji_json     — resolved gaiji references
 *  10. aozora_document_source_byte_len — owned source buffer length
 *  11. aozora_slugs_json              — document-independent slug table
 *  12. aozora_bytes_free              — release returned buffers
 *  13. aozora_document_free           — release the document handle
 *
 * It also checks the input-size guard: a src_len greater than
 * UINT32_MAX must return SOURCE_TOO_LARGE (-5) instead of driving the
 * parser core into its u32-span assert (which, under panic = "abort",
 * would abort this process).
 *
 * Build / run is driven by `tests/c_smoke/run.sh` (which builds the
 * cdylib first, then compiles and runs this program). Returns 0 on
 * success, non-zero on any unexpected status code or content.
 *
 * The C ABI is consumed through the cbindgen-generated `aozora.h`
 * (emitted by `build.rs` into the build's output dir and mirrored to
 * `target/<profile>/aozora.h`); run.sh points the compiler at it with
 * `-I`. Including the generated header — rather than hand-mirroring the
 * prototypes — makes any ABI signature drift a compile error.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>

/* The public C ABI, generated by cbindgen (build.rs -> aozora.h). */
#include "aozora.h"

/* --- Test --- */

static int check(const char *what, int condition) {
    if (!condition) {
        fprintf(stderr, "FAIL: %s\n", what);
        return 1;
    }
    return 0;
}

int main(void) {
    int failures = 0;
    char empty_envelope[64];
    int empty_envelope_len =
        snprintf(empty_envelope, sizeof(empty_envelope),
                 "{\"schemaVersion\":%u,\"data\":[]}", AOZORA_SCHEMA_VERSION);
    failures += check("wire expectation fits buffer",
                      empty_envelope_len > 0 &&
                          (size_t)empty_envelope_len < sizeof(empty_envelope));

    /* 1. parse "Hello, world." */
    const char *src = "Hello, world.";
    AozoraDocument *doc = NULL;
    int32_t status = aozora_document_new((const uint8_t *)src, strlen(src), &doc);
    failures += check("aozora_document_new returns Ok", status == 0);
    failures += check("aozora_document_new produces non-null handle", doc != NULL);

    /* 2. render HTML */
    AozoraBytes html = {NULL, 0, 0};
    status = aozora_document_to_html(doc, &html);
    failures += check("aozora_document_to_html returns Ok", status == 0);
    failures += check("html buffer is non-empty", html.len > 0);

    /* HTML output must contain "Hello" somewhere. We don't pin the
     * exact serialisation — the renderer can wrap things in tags as
     * it pleases. */
    char *html_str = (char *)malloc(html.len + 1);
    memcpy(html_str, html.ptr, html.len);
    html_str[html.len] = '\0';
    failures += check("html contains \"Hello\"", strstr(html_str, "Hello") != NULL);
    free(html_str);
    aozora_bytes_free(html);

    /* 3. diagnostics — envelope-shaped JSON for clean input. */
    AozoraBytes diag = {NULL, 0, 0};
    status = aozora_document_diagnostics_json(doc, &diag);
    failures += check("aozora_document_diagnostics_json returns Ok", status == 0);
    failures += check("diagnostics JSON is the empty envelope",
                      diag.len == (size_t)empty_envelope_len &&
                          memcmp(diag.ptr, empty_envelope,
                                 (size_t)empty_envelope_len) == 0);
    aozora_bytes_free(diag);

    /* 3b. round-trip source — to_source re-emits canonical Aozora
     *     source. Plain text round-trips to itself. */
    AozoraBytes source = {NULL, 0, 0};
    status = aozora_document_to_source(doc, &source);
    failures += check("aozora_document_to_source returns Ok", status == 0);
    failures += check("source buffer is non-empty", source.len > 0);
    char *source_str = (char *)malloc(source.len + 1);
    memcpy(source_str, source.ptr, source.len);
    source_str[source.len] = '\0';
    failures += check("round-trip source contains \"Hello\"",
                      strstr(source_str, "Hello") != NULL);
    free(source_str);
    aozora_bytes_free(source);

    /* 3c. container pairs — envelope-shaped JSON; inline-only input has
     *     no block enclosures, so the empty envelope. */
    AozoraBytes cpairs = {NULL, 0, 0};
    status = aozora_document_container_pairs_json(doc, &cpairs);
    failures += check("aozora_document_container_pairs_json returns Ok", status == 0);
    failures += check("container-pairs JSON is the empty envelope",
                      cpairs.len == (size_t)empty_envelope_len &&
                          memcmp(cpairs.ptr, empty_envelope,
                                 (size_t)empty_envelope_len) == 0);
    aozora_bytes_free(cpairs);

    /* 3d. gaiji — no gaiji directive in this source, so the empty
     *     envelope. */
    AozoraBytes gaiji = {NULL, 0, 0};
    status = aozora_document_gaiji_json(doc, &gaiji);
    failures += check("aozora_document_gaiji_json returns Ok", status == 0);
    failures += check("gaiji JSON is the empty envelope",
                      gaiji.len == (size_t)empty_envelope_len &&
                          memcmp(gaiji.ptr, empty_envelope,
                                 (size_t)empty_envelope_len) == 0);
    aozora_bytes_free(gaiji);

    /* 3e. source byte length — equals strlen(src) for this ASCII input. */
    size_t src_len = 0;
    status = aozora_document_source_byte_len(doc, &src_len);
    failures += check("aozora_document_source_byte_len returns Ok", status == 0);
    failures += check("source byte length equals input length",
                      src_len == strlen(src));

    /* 3f. slug catalogue — document-independent, envelope-shaped, and
     *     non-empty (the spec ships a populated slug table). */
    AozoraBytes slugs = {NULL, 0, 0};
    status = aozora_slugs_json(&slugs);
    failures += check("aozora_slugs_json returns Ok", status == 0);
    failures += check("slug catalogue JSON is non-empty", slugs.len > 0);
    {
        char *slugs_str = (char *)malloc(slugs.len + 1);
        memcpy(slugs_str, slugs.ptr, slugs.len);
        slugs_str[slugs.len] = '\0';
        failures += check("slug catalogue carries the wire envelope",
                          strstr(slugs_str, "schemaVersion") != NULL &&
                          strstr(slugs_str, "data") != NULL);
        free(slugs_str);
    }
    aozora_bytes_free(slugs);

    /* 4. free the document */
    aozora_document_free(doc);

    /* 5. null input — must return NullInput status */
    AozoraDocument *bad = NULL;
    status = aozora_document_new(NULL, 0, &bad);
    failures += check("null src returns NullInput status", status == -1);
    failures += check("null src leaves out_doc null", bad == NULL);

    /* 6. PUA collision — must yield a diagnostic */
    const char *pua = "abc\xEE\x80\x81 def"; /* U+E001 in UTF-8 = EE 80 81 */
    AozoraDocument *pua_doc = NULL;
    status = aozora_document_new((const uint8_t *)pua, strlen(pua), &pua_doc);
    failures += check("PUA-source aozora_document_new Ok", status == 0);
    AozoraBytes pua_diag = {NULL, 0, 0};
    status = aozora_document_diagnostics_json(pua_doc, &pua_diag);
    failures += check("PUA diagnostics call Ok", status == 0);
    char *pua_diag_str = (char *)malloc(pua_diag.len + 1);
    memcpy(pua_diag_str, pua_diag.ptr, pua_diag.len);
    pua_diag_str[pua_diag.len] = '\0';
    failures += check("PUA diagnostics mention source_contains_pua",
                      strstr(pua_diag_str, "source_contains_pua") != NULL);
    free(pua_diag_str);
    aozora_bytes_free(pua_diag);

    /* 6b. plain-text diagnostics — the miette-free portable render.
     *     The same PUA diagnostic must surface in human text, carrying
     *     its `aozora::` code. A clean parse would yield zero bytes. */
    AozoraBytes pua_text = {NULL, 0, 0};
    status = aozora_document_diagnostics_text(pua_doc, &pua_text);
    failures += check("aozora_document_diagnostics_text returns Ok", status == 0);
    failures += check("plain-text diagnostics are non-empty", pua_text.len > 0);
    char *pua_text_str = (char *)malloc(pua_text.len + 1);
    memcpy(pua_text_str, pua_text.ptr, pua_text.len);
    pua_text_str[pua_text.len] = '\0';
    failures += check("plain-text diagnostics carry the aozora:: code",
                      strstr(pua_text_str, "aozora::") != NULL);
    free(pua_text_str);
    aozora_bytes_free(pua_text);
    aozora_document_free(pua_doc);

    /* 7. oversize input — src_len > UINT32_MAX must return
     *    AOZORA_SOURCE_TOO_LARGE (-5). The guard checks src_len before
     *    dereferencing src_ptr, so a non-null dangling pointer with a
     *    fabricated huge length is safe: the call returns before any
     *    read. Skip where size_t cannot hold UINT32_MAX + 1. */
#if SIZE_MAX > 0xFFFFFFFFu
    {
        /* Non-null but never dereferenced. */
        uint8_t sentinel = 0;
        const uint8_t *dangling = &sentinel;
        size_t oversize = (size_t)0xFFFFFFFFu + 1u;
        AozoraDocument *huge = NULL;
        status = aozora_document_new(dangling, oversize, &huge);
        failures += check("oversize src_len returns SourceTooLarge", status == -5);
        failures += check("oversize src_len leaves out_doc null", huge == NULL);
    }
#endif

    if (failures == 0) {
        printf("c_smoke: all checks passed\n");
        return 0;
    }
    fprintf(stderr, "c_smoke: %d check(s) failed\n", failures);
    return 1;
}
